// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmosorderbook/batch/v1/query.proto

package v1

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryBatchRequest struct {
	BatchNumber          uint64   `protobuf:"varint,1,opt,name=batch_number,json=batchNumber,proto3" json:"batch_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryBatchRequest) Reset()         { *m = QueryBatchRequest{} }
func (m *QueryBatchRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBatchRequest) ProtoMessage()    {}
func (*QueryBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8bb44cf3b31d553, []int{0}
}
func (m *QueryBatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryBatchRequest.Unmarshal(m, b)
}
func (m *QueryBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryBatchRequest.Marshal(b, m, deterministic)
}
func (m *QueryBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBatchRequest.Merge(m, src)
}
func (m *QueryBatchRequest) XXX_Size() int {
	return xxx_messageInfo_QueryBatchRequest.Size(m)
}
func (m *QueryBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBatchRequest proto.InternalMessageInfo

func (m *QueryBatchRequest) GetBatchNumber() uint64 {
	if m != nil {
		return m.BatchNumber
	}
	return 0
}

type QueryBatchResponse struct {
	Batch                *Batch   `protobuf:"bytes,1,opt,name=batch,proto3" json:"batch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryBatchResponse) Reset()         { *m = QueryBatchResponse{} }
func (m *QueryBatchResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBatchResponse) ProtoMessage()    {}
func (*QueryBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8bb44cf3b31d553, []int{1}
}
func (m *QueryBatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryBatchResponse.Unmarshal(m, b)
}
func (m *QueryBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryBatchResponse.Marshal(b, m, deterministic)
}
func (m *QueryBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBatchResponse.Merge(m, src)
}
func (m *QueryBatchResponse) XXX_Size() int {
	return xxx_messageInfo_QueryBatchResponse.Size(m)
}
func (m *QueryBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBatchResponse proto.InternalMessageInfo

func (m *QueryBatchResponse) GetBatch() *Batch {
	if m != nil {
		return m.Batch
	}
	return nil
}

type QueryLatestBatchRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryLatestBatchRequest) Reset()         { *m = QueryLatestBatchRequest{} }
func (m *QueryLatestBatchRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLatestBatchRequest) ProtoMessage()    {}
func (*QueryLatestBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8bb44cf3b31d553, []int{2}
}
func (m *QueryLatestBatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryLatestBatchRequest.Unmarshal(m, b)
}
func (m *QueryLatestBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryLatestBatchRequest.Marshal(b, m, deterministic)
}
func (m *QueryLatestBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLatestBatchRequest.Merge(m, src)
}
func (m *QueryLatestBatchRequest) XXX_Size() int {
	return xxx_messageInfo_QueryLatestBatchRequest.Size(m)
}
func (m *QueryLatestBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLatestBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLatestBatchRequest proto.InternalMessageInfo

type QueryLatestBatchResponse struct {
	Batch                *Batch   `protobuf:"bytes,1,opt,name=batch,proto3" json:"batch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryLatestBatchResponse) Reset()         { *m = QueryLatestBatchResponse{} }
func (m *QueryLatestBatchResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLatestBatchResponse) ProtoMessage()    {}
func (*QueryLatestBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8bb44cf3b31d553, []int{3}
}
func (m *QueryLatestBatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryLatestBatchResponse.Unmarshal(m, b)
}
func (m *QueryLatestBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryLatestBatchResponse.Marshal(b, m, deterministic)
}
func (m *QueryLatestBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLatestBatchResponse.Merge(m, src)
}
func (m *QueryLatestBatchResponse) XXX_Size() int {
	return xxx_messageInfo_QueryLatestBatchResponse.Size(m)
}
func (m *QueryLatestBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLatestBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLatestBatchResponse proto.InternalMessageInfo

func (m *QueryLatestBatchResponse) GetBatch() *Batch {
	if m != nil {
		return m.Batch
	}
	return nil
}

type QueryBatchByIDRequest struct {
	BatchId              []byte   `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryBatchByIDRequest) Reset()         { *m = QueryBatchByIDRequest{} }
func (m *QueryBatchByIDRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBatchByIDRequest) ProtoMessage()    {}
func (*QueryBatchByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8bb44cf3b31d553, []int{4}
}
func (m *QueryBatchByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryBatchByIDRequest.Unmarshal(m, b)
}
func (m *QueryBatchByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryBatchByIDRequest.Marshal(b, m, deterministic)
}
func (m *QueryBatchByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBatchByIDRequest.Merge(m, src)
}
func (m *QueryBatchByIDRequest) XXX_Size() int {
	return xxx_messageInfo_QueryBatchByIDRequest.Size(m)
}
func (m *QueryBatchByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBatchByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBatchByIDRequest proto.InternalMessageInfo

func (m *QueryBatchByIDRequest) GetBatchId() []byte {
	if m != nil {
		return m.BatchId
	}
	return nil
}

type QueryBatchByIDResponse struct {
	Batch                *Batch   `protobuf:"bytes,1,opt,name=batch,proto3" json:"batch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryBatchByIDResponse) Reset()         { *m = QueryBatchByIDResponse{} }
func (m *QueryBatchByIDResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBatchByIDResponse) ProtoMessage()    {}
func (*QueryBatchByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8bb44cf3b31d553, []int{5}
}
func (m *QueryBatchByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryBatchByIDResponse.Unmarshal(m, b)
}
func (m *QueryBatchByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryBatchByIDResponse.Marshal(b, m, deterministic)
}
func (m *QueryBatchByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBatchByIDResponse.Merge(m, src)
}
func (m *QueryBatchByIDResponse) XXX_Size() int {
	return xxx_messageInfo_QueryBatchByIDResponse.Size(m)
}
func (m *QueryBatchByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBatchByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBatchByIDResponse proto.InternalMessageInfo

func (m *QueryBatchByIDResponse) GetBatch() *Batch {
	if m != nil {
		return m.Batch
	}
	return nil
}

type QueryBatchCommitmentRequest struct {
	BatchNumber          uint64   `protobuf:"varint,1,opt,name=batch_number,json=batchNumber,proto3" json:"batch_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryBatchCommitmentRequest) Reset()         { *m = QueryBatchCommitmentRequest{} }
func (m *QueryBatchCommitmentRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBatchCommitmentRequest) ProtoMessage()    {}
func (*QueryBatchCommitmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8bb44cf3b31d553, []int{6}
}
func (m *QueryBatchCommitmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryBatchCommitmentRequest.Unmarshal(m, b)
}
func (m *QueryBatchCommitmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryBatchCommitmentRequest.Marshal(b, m, deterministic)
}
func (m *QueryBatchCommitmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBatchCommitmentRequest.Merge(m, src)
}
func (m *QueryBatchCommitmentRequest) XXX_Size() int {
	return xxx_messageInfo_QueryBatchCommitmentRequest.Size(m)
}
func (m *QueryBatchCommitmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBatchCommitmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBatchCommitmentRequest proto.InternalMessageInfo

func (m *QueryBatchCommitmentRequest) GetBatchNumber() uint64 {
	if m != nil {
		return m.BatchNumber
	}
	return 0
}

type QueryBatchCommitmentResponse struct {
	BatchNumber             uint64   `protobuf:"varint,1,opt,name=batch_number,json=batchNumber,proto3" json:"batch_number,omitempty"`
	BatchId                 []byte   `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	PreviousBatchCommitment []byte   `protobuf:"bytes,3,opt,name=previous_batch_commitment,json=previousBatchCommitment,proto3" json:"previous_batch_commitment,omitempty"`
	BatchCommitment         []byte   `protobuf:"bytes,4,opt,name=batch_commitment,json=batchCommitment,proto3" json:"batch_commitment,omitempty"`
	ResultsHash             []byte   `protobuf:"bytes,5,opt,name=results_hash,json=resultsHash,proto3" json:"results_hash,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *QueryBatchCommitmentResponse) Reset()         { *m = QueryBatchCommitmentResponse{} }
func (m *QueryBatchCommitmentResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBatchCommitmentResponse) ProtoMessage()    {}
func (*QueryBatchCommitmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8bb44cf3b31d553, []int{7}
}
func (m *QueryBatchCommitmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryBatchCommitmentResponse.Unmarshal(m, b)
}
func (m *QueryBatchCommitmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryBatchCommitmentResponse.Marshal(b, m, deterministic)
}
func (m *QueryBatchCommitmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBatchCommitmentResponse.Merge(m, src)
}
func (m *QueryBatchCommitmentResponse) XXX_Size() int {
	return xxx_messageInfo_QueryBatchCommitmentResponse.Size(m)
}
func (m *QueryBatchCommitmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBatchCommitmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBatchCommitmentResponse proto.InternalMessageInfo

func (m *QueryBatchCommitmentResponse) GetBatchNumber() uint64 {
	if m != nil {
		return m.BatchNumber
	}
	return 0
}

func (m *QueryBatchCommitmentResponse) GetBatchId() []byte {
	if m != nil {
		return m.BatchId
	}
	return nil
}

func (m *QueryBatchCommitmentResponse) GetPreviousBatchCommitment() []byte {
	if m != nil {
		return m.PreviousBatchCommitment
	}
	return nil
}

func (m *QueryBatchCommitmentResponse) GetBatchCommitment() []byte {
	if m != nil {
		return m.BatchCommitment
	}
	return nil
}

func (m *QueryBatchCommitmentResponse) GetResultsHash() []byte {
	if m != nil {
		return m.ResultsHash
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryBatchRequest)(nil), "cosmosorderbook.batch.v1.QueryBatchRequest")
	proto.RegisterType((*QueryBatchResponse)(nil), "cosmosorderbook.batch.v1.QueryBatchResponse")
	proto.RegisterType((*QueryLatestBatchRequest)(nil), "cosmosorderbook.batch.v1.QueryLatestBatchRequest")
	proto.RegisterType((*QueryLatestBatchResponse)(nil), "cosmosorderbook.batch.v1.QueryLatestBatchResponse")
	proto.RegisterType((*QueryBatchByIDRequest)(nil), "cosmosorderbook.batch.v1.QueryBatchByIDRequest")
	proto.RegisterType((*QueryBatchByIDResponse)(nil), "cosmosorderbook.batch.v1.QueryBatchByIDResponse")
	proto.RegisterType((*QueryBatchCommitmentRequest)(nil), "cosmosorderbook.batch.v1.QueryBatchCommitmentRequest")
	proto.RegisterType((*QueryBatchCommitmentResponse)(nil), "cosmosorderbook.batch.v1.QueryBatchCommitmentResponse")
}

func init() {
	proto.RegisterFile("cosmosorderbook/batch/v1/query.proto", fileDescriptor_d8bb44cf3b31d553)
}

var fileDescriptor_d8bb44cf3b31d553 = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xdf, 0x8e, 0x93, 0x40,
	0x14, 0xc6, 0x83, 0xbb, 0xf8, 0xe7, 0xd0, 0x64, 0x75, 0x12, 0x5d, 0x8a, 0x26, 0xba, 0xc4, 0x0b,
	0x8d, 0x2e, 0x53, 0x30, 0xdd, 0x0b, 0xaf, 0x4c, 0x57, 0x13, 0x37, 0x1a, 0xcd, 0xf6, 0xd2, 0x9b,
	0x06, 0xe8, 0x64, 0x21, 0x0a, 0xc3, 0xce, 0x0c, 0x44, 0xee, 0x7c, 0x48, 0x9f, 0xc1, 0xe7, 0x30,
	0x7b, 0xa0, 0x2d, 0x85, 0x6d, 0x4a, 0xd3, 0x4b, 0x86, 0xef, 0xf7, 0x9d, 0xef, 0xcc, 0x9c, 0x1c,
	0x78, 0x19, 0x72, 0x99, 0x70, 0xc9, 0xc5, 0x9c, 0x89, 0x80, 0xf3, 0x9f, 0x34, 0xf0, 0x55, 0x18,
	0xd1, 0xc2, 0xa5, 0xd7, 0x39, 0x13, 0xa5, 0x93, 0x09, 0xae, 0x38, 0x31, 0x5b, 0x2a, 0x07, 0x55,
	0x4e, 0xe1, 0x5a, 0x9b, 0x79, 0x55, 0x66, 0x4c, 0x56, 0xbc, 0x7d, 0x06, 0x8f, 0x2e, 0x6f, 0xec,
	0x26, 0x37, 0x3f, 0xa7, 0xec, 0x3a, 0x67, 0x52, 0x91, 0x13, 0x18, 0xa0, 0x78, 0x96, 0xe6, 0x49,
	0xc0, 0x84, 0xa9, 0xbd, 0xd0, 0x5e, 0x1d, 0x4e, 0x0d, 0x3c, 0xfb, 0x86, 0x47, 0xf6, 0x17, 0x20,
	0x4d, 0x4e, 0x66, 0x3c, 0x95, 0x8c, 0x8c, 0x41, 0x47, 0x11, 0x12, 0x86, 0xf7, 0xdc, 0xd9, 0x94,
	0xce, 0xa9, 0xb8, 0x4a, 0x6d, 0x0f, 0xe1, 0x18, 0xcd, 0xbe, 0xfa, 0x8a, 0x49, 0xd5, 0x8c, 0x62,
	0x5f, 0x82, 0xd9, 0xfd, 0xb5, 0x5f, 0x35, 0x0f, 0x1e, 0xaf, 0xa2, 0x4f, 0xca, 0x8b, 0x8f, 0x8b,
	0xb6, 0x87, 0x70, 0xbf, 0x6a, 0x3b, 0x9e, 0xa3, 0xe5, 0x60, 0x7a, 0x0f, 0xbf, 0x2f, 0xe6, 0xf6,
	0x77, 0x78, 0xd2, 0x66, 0xf6, 0x0b, 0xf1, 0x01, 0x9e, 0xae, 0x0c, 0xcf, 0x79, 0x92, 0xc4, 0x2a,
	0x61, 0xa9, 0xda, 0xe1, 0x05, 0xfe, 0x69, 0xf0, 0xec, 0x76, 0x8b, 0x3a, 0xd9, 0x76, 0x8f, 0xb5,
	0x8e, 0xef, 0xac, 0x75, 0x4c, 0xde, 0xc3, 0x30, 0x13, 0xac, 0x88, 0x79, 0x2e, 0x67, 0x95, 0x26,
	0x5c, 0x96, 0x30, 0x0f, 0x50, 0x7b, 0xbc, 0x10, 0xb4, 0x12, 0x90, 0xd7, 0xf0, 0xb0, 0x83, 0x1c,
	0x22, 0x72, 0x14, 0xb4, 0xa4, 0x27, 0x30, 0x10, 0x4c, 0xe6, 0xbf, 0x94, 0x9c, 0x45, 0xbe, 0x8c,
	0x4c, 0x1d, 0x65, 0x46, 0x7d, 0xf6, 0xd9, 0x97, 0x91, 0xf7, 0xf7, 0x00, 0x74, 0x6c, 0x94, 0x04,
	0xa0, 0x63, 0x29, 0xf2, 0x66, 0xf3, 0x2d, 0x77, 0xa6, 0xd9, 0x7a, 0xdb, 0x4f, 0x5c, 0xdf, 0x9a,
	0x02, 0xa3, 0x31, 0x6b, 0xc4, 0xdd, 0x02, 0x77, 0x47, 0xd6, 0xf2, 0x76, 0x41, 0xea, 0xaa, 0x29,
	0x3c, 0x58, 0x8e, 0x16, 0xa1, 0x7d, 0x02, 0x37, 0x06, 0xd7, 0x1a, 0xf5, 0x07, 0xea, 0x7a, 0x7f,
	0x34, 0x38, 0x6a, 0xbf, 0xda, 0xb8, 0x8f, 0x4b, 0x67, 0x54, 0xad, 0xb3, 0x5d, 0xb1, 0x2a, 0xc2,
	0xe4, 0xd3, 0x8f, 0xf3, 0xab, 0x58, 0x45, 0x79, 0xe0, 0x84, 0x3c, 0xa1, 0x7e, 0x99, 0xcb, 0x28,
	0x89, 0x65, 0x24, 0x7c, 0x6f, 0x34, 0x1a, 0xd3, 0xca, 0xf3, 0x74, 0x69, 0x7a, 0xca, 0xd2, 0xab,
	0x38, 0x65, 0xf4, 0x77, 0xbd, 0xc6, 0x70, 0x87, 0xd1, 0xc2, 0x0d, 0xee, 0xe2, 0x1e, 0x7b, 0xf7,
	0x7f, 0x00, 0x17, 0x2b, 0x6d, 0x9a, 0x2f, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Batch(ctx context.Context, in *QueryBatchRequest, opts ...grpc.CallOption) (*QueryBatchResponse, error)
	LatestBatch(ctx context.Context, in *QueryLatestBatchRequest, opts ...grpc.CallOption) (*QueryLatestBatchResponse, error)
	BatchByID(ctx context.Context, in *QueryBatchByIDRequest, opts ...grpc.CallOption) (*QueryBatchByIDResponse, error)
	BatchCommitment(ctx context.Context, in *QueryBatchCommitmentRequest, opts ...grpc.CallOption) (*QueryBatchCommitmentResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Batch(ctx context.Context, in *QueryBatchRequest, opts ...grpc.CallOption) (*QueryBatchResponse, error) {
	out := new(QueryBatchResponse)
	err := c.cc.Invoke(ctx, "/cosmosorderbook.batch.v1.Query/Batch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LatestBatch(ctx context.Context, in *QueryLatestBatchRequest, opts ...grpc.CallOption) (*QueryLatestBatchResponse, error) {
	out := new(QueryLatestBatchResponse)
	err := c.cc.Invoke(ctx, "/cosmosorderbook.batch.v1.Query/LatestBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BatchByID(ctx context.Context, in *QueryBatchByIDRequest, opts ...grpc.CallOption) (*QueryBatchByIDResponse, error) {
	out := new(QueryBatchByIDResponse)
	err := c.cc.Invoke(ctx, "/cosmosorderbook.batch.v1.Query/BatchByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BatchCommitment(ctx context.Context, in *QueryBatchCommitmentRequest, opts ...grpc.CallOption) (*QueryBatchCommitmentResponse, error) {
	out := new(QueryBatchCommitmentResponse)
	err := c.cc.Invoke(ctx, "/cosmosorderbook.batch.v1.Query/BatchCommitment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Batch(context.Context, *QueryBatchRequest) (*QueryBatchResponse, error)
	LatestBatch(context.Context, *QueryLatestBatchRequest) (*QueryLatestBatchResponse, error)
	BatchByID(context.Context, *QueryBatchByIDRequest) (*QueryBatchByIDResponse, error)
	BatchCommitment(context.Context, *QueryBatchCommitmentRequest) (*QueryBatchCommitmentResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Batch(ctx context.Context, req *QueryBatchRequest) (*QueryBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Batch not implemented")
}
func (*UnimplementedQueryServer) LatestBatch(ctx context.Context, req *QueryLatestBatchRequest) (*QueryLatestBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LatestBatch not implemented")
}
func (*UnimplementedQueryServer) BatchByID(ctx context.Context, req *QueryBatchByIDRequest) (*QueryBatchByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchByID not implemented")
}
func (*UnimplementedQueryServer) BatchCommitment(ctx context.Context, req *QueryBatchCommitmentRequest) (*QueryBatchCommitmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchCommitment not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Batch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Batch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmosorderbook.batch.v1.Query/Batch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Batch(ctx, req.(*QueryBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LatestBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLatestBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LatestBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmosorderbook.batch.v1.Query/LatestBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LatestBatch(ctx, req.(*QueryLatestBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BatchByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBatchByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BatchByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmosorderbook.batch.v1.Query/BatchByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BatchByID(ctx, req.(*QueryBatchByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BatchCommitment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBatchCommitmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BatchCommitment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmosorderbook.batch.v1.Query/BatchCommitment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BatchCommitment(ctx, req.(*QueryBatchCommitmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmosorderbook.batch.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Batch",
			Handler:    _Query_Batch_Handler,
		},
		{
			MethodName: "LatestBatch",
			Handler:    _Query_LatestBatch_Handler,
		},
		{
			MethodName: "BatchByID",
			Handler:    _Query_BatchByID_Handler,
		},
		{
			MethodName: "BatchCommitment",
			Handler:    _Query_BatchCommitment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmosorderbook/batch/v1/query.proto",
}
