// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmosorderbook/batch/v1/tx.proto

package v1

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgFinalizeBatch executes ordered signed commands as one batch.
// The submitter authorizes inclusion. Each command is signed by its owner.
type MsgFinalizeBatch struct {
	Submitter                string           `protobuf:"bytes,1,opt,name=submitter,proto3" json:"submitter,omitempty"`
	BatchNumber              uint64           `protobuf:"varint,2,opt,name=batch_number,json=batchNumber,proto3" json:"batch_number,omitempty"`
	ExpectedExchangeRevision uint64           `protobuf:"varint,3,opt,name=expected_exchange_revision,json=expectedExchangeRevision,proto3" json:"expected_exchange_revision,omitempty"`
	Commands                 []*SignedCommand `protobuf:"bytes,4,rep,name=commands,proto3" json:"commands,omitempty"`
	// Previous commitment of the current head. Batch 1 uses 32 zero bytes.
	PreviousBatchCommitment []byte   `protobuf:"bytes,5,opt,name=previous_batch_commitment,json=previousBatchCommitment,proto3" json:"previous_batch_commitment,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *MsgFinalizeBatch) Reset()         { *m = MsgFinalizeBatch{} }
func (m *MsgFinalizeBatch) String() string { return proto.CompactTextString(m) }
func (*MsgFinalizeBatch) ProtoMessage()    {}
func (*MsgFinalizeBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_2570430717ff18c0, []int{0}
}
func (m *MsgFinalizeBatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgFinalizeBatch.Unmarshal(m, b)
}
func (m *MsgFinalizeBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgFinalizeBatch.Marshal(b, m, deterministic)
}
func (m *MsgFinalizeBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFinalizeBatch.Merge(m, src)
}
func (m *MsgFinalizeBatch) XXX_Size() int {
	return xxx_messageInfo_MsgFinalizeBatch.Size(m)
}
func (m *MsgFinalizeBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFinalizeBatch.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFinalizeBatch proto.InternalMessageInfo

func (m *MsgFinalizeBatch) GetSubmitter() string {
	if m != nil {
		return m.Submitter
	}
	return ""
}

func (m *MsgFinalizeBatch) GetBatchNumber() uint64 {
	if m != nil {
		return m.BatchNumber
	}
	return 0
}

func (m *MsgFinalizeBatch) GetExpectedExchangeRevision() uint64 {
	if m != nil {
		return m.ExpectedExchangeRevision
	}
	return 0
}

func (m *MsgFinalizeBatch) GetCommands() []*SignedCommand {
	if m != nil {
		return m.Commands
	}
	return nil
}

func (m *MsgFinalizeBatch) GetPreviousBatchCommitment() []byte {
	if m != nil {
		return m.PreviousBatchCommitment
	}
	return nil
}

type MsgFinalizeBatchResponse struct {
	BatchId              []byte           `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	PostExchangeRevision uint64           `protobuf:"varint,2,opt,name=post_exchange_revision,json=postExchangeRevision,proto3" json:"post_exchange_revision,omitempty"`
	Results              []*CommandResult `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	BatchCommitment      []byte           `protobuf:"bytes,4,opt,name=batch_commitment,json=batchCommitment,proto3" json:"batch_commitment,omitempty"`
	ResultsHash          []byte           `protobuf:"bytes,5,opt,name=results_hash,json=resultsHash,proto3" json:"results_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MsgFinalizeBatchResponse) Reset()         { *m = MsgFinalizeBatchResponse{} }
func (m *MsgFinalizeBatchResponse) String() string { return proto.CompactTextString(m) }
func (*MsgFinalizeBatchResponse) ProtoMessage()    {}
func (*MsgFinalizeBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2570430717ff18c0, []int{1}
}
func (m *MsgFinalizeBatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgFinalizeBatchResponse.Unmarshal(m, b)
}
func (m *MsgFinalizeBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgFinalizeBatchResponse.Marshal(b, m, deterministic)
}
func (m *MsgFinalizeBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFinalizeBatchResponse.Merge(m, src)
}
func (m *MsgFinalizeBatchResponse) XXX_Size() int {
	return xxx_messageInfo_MsgFinalizeBatchResponse.Size(m)
}
func (m *MsgFinalizeBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFinalizeBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFinalizeBatchResponse proto.InternalMessageInfo

func (m *MsgFinalizeBatchResponse) GetBatchId() []byte {
	if m != nil {
		return m.BatchId
	}
	return nil
}

func (m *MsgFinalizeBatchResponse) GetPostExchangeRevision() uint64 {
	if m != nil {
		return m.PostExchangeRevision
	}
	return 0
}

func (m *MsgFinalizeBatchResponse) GetResults() []*CommandResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *MsgFinalizeBatchResponse) GetBatchCommitment() []byte {
	if m != nil {
		return m.BatchCommitment
	}
	return nil
}

func (m *MsgFinalizeBatchResponse) GetResultsHash() []byte {
	if m != nil {
		return m.ResultsHash
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgFinalizeBatch)(nil), "cosmosorderbook.batch.v1.MsgFinalizeBatch")
	proto.RegisterType((*MsgFinalizeBatchResponse)(nil), "cosmosorderbook.batch.v1.MsgFinalizeBatchResponse")
}

func init() { proto.RegisterFile("cosmosorderbook/batch/v1/tx.proto", fileDescriptor_2570430717ff18c0) }

var fileDescriptor_2570430717ff18c0 = []byte{
	// 483 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x9b, 0x94, 0xb6, 0x9b, 0x00, 0xd5, 0xaa, 0xa2, 0x1b, 0x9f, 0xd2, 0x0a, 0x89, 0x10,
	0x29, 0x76, 0x13, 0x3e, 0x0e, 0x15, 0x97, 0x26, 0x2a, 0x82, 0x43, 0x39, 0xb8, 0x37, 0x2e, 0x96,
	0x3f, 0x56, 0xf6, 0x8a, 0xee, 0xae, 0xb5, 0xb3, 0x8e, 0x52, 0x24, 0x24, 0xc4, 0x2f, 0xea, 0x81,
	0x23, 0xbf, 0x82, 0x3f, 0xd1, 0x3f, 0xc1, 0x01, 0x79, 0xbd, 0x4e, 0xd5, 0x84, 0x88, 0x1e, 0x77,
	0xde, 0x7b, 0x33, 0xf3, 0x9e, 0x3d, 0xe8, 0x28, 0x91, 0xc0, 0x25, 0x48, 0x95, 0x52, 0x15, 0x4b,
	0xf9, 0xc5, 0x8f, 0x23, 0x9d, 0xe4, 0xfe, 0x7c, 0xec, 0xeb, 0x85, 0x57, 0x28, 0xa9, 0x25, 0x26,
	0x2b, 0x14, 0xcf, 0x50, 0xbc, 0xf9, 0xd8, 0x3d, 0xac, 0x11, 0x9f, 0x43, 0x56, 0x29, 0x38, 0x64,
	0xb5, 0xc4, 0xed, 0xd5, 0x40, 0x68, 0x5e, 0x7e, 0xfd, 0xb0, 0xd0, 0xf3, 0xcd, 0x03, 0xaf, 0x0b,
	0x6a, 0x59, 0xc7, 0xbf, 0xb6, 0xd0, 0xfe, 0x05, 0x64, 0xef, 0x99, 0x88, 0xae, 0xd8, 0x57, 0x3a,
	0xad, 0x38, 0xf8, 0x2d, 0xda, 0x83, 0x32, 0xe6, 0x4c, 0x6b, 0xaa, 0x88, 0xd3, 0x77, 0x06, 0x7b,
	0x53, 0xf2, 0xfb, 0xe7, 0xe8, 0xc0, 0xf6, 0x3f, 0x4b, 0x53, 0x45, 0x01, 0x2e, 0xb5, 0x62, 0x22,
	0x0b, 0xee, 0xa8, 0xf8, 0x08, 0x75, 0xcd, 0x90, 0x50, 0x94, 0x3c, 0xa6, 0x8a, 0x6c, 0xf5, 0x9d,
	0x41, 0x3b, 0xe8, 0x98, 0xda, 0x27, 0x53, 0xc2, 0xef, 0x90, 0x4b, 0x17, 0x05, 0x4d, 0x34, 0x4d,
	0x43, 0xba, 0x48, 0xf2, 0x48, 0x64, 0x34, 0x54, 0x74, 0xce, 0x80, 0x49, 0x41, 0x5a, 0x46, 0x40,
	0x1a, 0xc6, 0xb9, 0x25, 0x04, 0x16, 0xc7, 0x33, 0xb4, 0x9b, 0x48, 0xce, 0x23, 0x91, 0x02, 0x69,
	0xf7, 0x5b, 0x83, 0xce, 0xe4, 0x85, 0xb7, 0x29, 0x34, 0xef, 0x92, 0x65, 0x82, 0xa6, 0xb3, 0x9a,
	0x1f, 0x2c, 0x85, 0xf8, 0x14, 0xf5, 0x8a, 0x6a, 0xa2, 0x2c, 0x21, 0xac, 0xd7, 0xad, 0x20, 0xa6,
	0x39, 0x15, 0x9a, 0x6c, 0xf7, 0x9d, 0x41, 0x37, 0x38, 0x6c, 0x08, 0x26, 0x8f, 0xd9, 0x12, 0x3e,
	0x7d, 0xf2, 0xe3, 0xf6, 0x66, 0x78, 0xe7, 0xf8, 0xf8, 0x8f, 0x83, 0xc8, 0x6a, 0x7c, 0x01, 0x85,
	0x42, 0x0a, 0xa0, 0xb8, 0x87, 0x76, 0xeb, 0xfe, 0x2c, 0x35, 0x29, 0x76, 0x83, 0x1d, 0xf3, 0xfe,
	0x98, 0xe2, 0xd7, 0xe8, 0x59, 0x21, 0x41, 0xff, 0x23, 0x82, 0x3a, 0xb3, 0x83, 0x0a, 0x5d, 0xb3,
	0x7f, 0x86, 0x76, 0x14, 0x85, 0xf2, 0x4a, 0x03, 0x69, 0xfd, 0xcf, 0x7d, 0xe3, 0xdb, 0xf0, 0x83,
	0x46, 0x87, 0x5f, 0xa2, 0xfd, 0x35, 0xcf, 0x6d, 0xb3, 0xdb, 0xd3, 0xf8, 0xbe, 0xd7, 0xea, 0x6b,
	0x5a, 0x55, 0x98, 0x47, 0x90, 0xdb, 0x68, 0x3a, 0xb6, 0xf6, 0x21, 0x82, 0x7c, 0xf2, 0x0d, 0xb5,
	0x2e, 0x20, 0xc3, 0x12, 0x3d, 0xbe, 0xff, 0x03, 0x0d, 0x37, 0xef, 0xb5, 0x9a, 0x96, 0x3b, 0x79,
	0x38, 0xb7, 0x49, 0xd6, 0xdd, 0xfe, 0x7e, 0x7b, 0x33, 0x74, 0xa6, 0xe7, 0x9f, 0x67, 0x19, 0xd3,
	0x79, 0x19, 0x7b, 0x89, 0xe4, 0x7e, 0x74, 0x5d, 0x42, 0xce, 0x19, 0xe4, 0x2a, 0x9a, 0x9c, 0x9c,
	0xbc, 0xb1, 0xd7, 0x30, 0x5a, 0xf6, 0x1d, 0x51, 0x91, 0x31, 0x41, 0xfd, 0x85, 0xbd, 0x04, 0x73,
	0x06, 0xfe, 0x7c, 0x1c, 0x3f, 0x32, 0xa7, 0xf0, 0xea, 0xef, 0x00, 0xfc, 0x55, 0x68, 0x5a, 0xa3,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	FinalizeBatch(ctx context.Context, in *MsgFinalizeBatch, opts ...grpc.CallOption) (*MsgFinalizeBatchResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) FinalizeBatch(ctx context.Context, in *MsgFinalizeBatch, opts ...grpc.CallOption) (*MsgFinalizeBatchResponse, error) {
	out := new(MsgFinalizeBatchResponse)
	err := c.cc.Invoke(ctx, "/cosmosorderbook.batch.v1.Msg/FinalizeBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	FinalizeBatch(context.Context, *MsgFinalizeBatch) (*MsgFinalizeBatchResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) FinalizeBatch(ctx context.Context, req *MsgFinalizeBatch) (*MsgFinalizeBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeBatch not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_FinalizeBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgFinalizeBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).FinalizeBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmosorderbook.batch.v1.Msg/FinalizeBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).FinalizeBatch(ctx, req.(*MsgFinalizeBatch))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmosorderbook.batch.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FinalizeBatch",
			Handler:    _Msg_FinalizeBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmosorderbook/batch/v1/tx.proto",
}
