// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmosorderbook/batch/v1/tx.proto

package v1

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgFinalizeBatch executes ordered signed commands as one batch.
// The submitter authorizes inclusion. Each command is signed by its owner.
type MsgFinalizeBatch struct {
	Submitter                string           `protobuf:"bytes,1,opt,name=submitter,proto3" json:"submitter,omitempty"`
	BatchNumber              uint64           `protobuf:"varint,2,opt,name=batch_number,json=batchNumber,proto3" json:"batch_number,omitempty"`
	ExpectedExchangeRevision uint64           `protobuf:"varint,3,opt,name=expected_exchange_revision,json=expectedExchangeRevision,proto3" json:"expected_exchange_revision,omitempty"`
	Commands                 []*SignedCommand `protobuf:"bytes,4,rep,name=commands,proto3" json:"commands,omitempty"`
}

func (m *MsgFinalizeBatch) Reset()         { *m = MsgFinalizeBatch{} }
func (m *MsgFinalizeBatch) String() string { return proto.CompactTextString(m) }
func (*MsgFinalizeBatch) ProtoMessage()    {}
func (*MsgFinalizeBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_2570430717ff18c0, []int{0}
}
func (m *MsgFinalizeBatch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFinalizeBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFinalizeBatch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFinalizeBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFinalizeBatch.Merge(m, src)
}
func (m *MsgFinalizeBatch) XXX_Size() int {
	return m.Size()
}
func (m *MsgFinalizeBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFinalizeBatch.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFinalizeBatch proto.InternalMessageInfo

func (m *MsgFinalizeBatch) GetSubmitter() string {
	if m != nil {
		return m.Submitter
	}
	return ""
}

func (m *MsgFinalizeBatch) GetBatchNumber() uint64 {
	if m != nil {
		return m.BatchNumber
	}
	return 0
}

func (m *MsgFinalizeBatch) GetExpectedExchangeRevision() uint64 {
	if m != nil {
		return m.ExpectedExchangeRevision
	}
	return 0
}

func (m *MsgFinalizeBatch) GetCommands() []*SignedCommand {
	if m != nil {
		return m.Commands
	}
	return nil
}

type MsgFinalizeBatchResponse struct {
	BatchId              []byte           `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	PostExchangeRevision uint64           `protobuf:"varint,2,opt,name=post_exchange_revision,json=postExchangeRevision,proto3" json:"post_exchange_revision,omitempty"`
	Results              []*CommandResult `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
}

func (m *MsgFinalizeBatchResponse) Reset()         { *m = MsgFinalizeBatchResponse{} }
func (m *MsgFinalizeBatchResponse) String() string { return proto.CompactTextString(m) }
func (*MsgFinalizeBatchResponse) ProtoMessage()    {}
func (*MsgFinalizeBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2570430717ff18c0, []int{1}
}
func (m *MsgFinalizeBatchResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFinalizeBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFinalizeBatchResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFinalizeBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFinalizeBatchResponse.Merge(m, src)
}
func (m *MsgFinalizeBatchResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgFinalizeBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFinalizeBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFinalizeBatchResponse proto.InternalMessageInfo

func (m *MsgFinalizeBatchResponse) GetBatchId() []byte {
	if m != nil {
		return m.BatchId
	}
	return nil
}

func (m *MsgFinalizeBatchResponse) GetPostExchangeRevision() uint64 {
	if m != nil {
		return m.PostExchangeRevision
	}
	return 0
}

func (m *MsgFinalizeBatchResponse) GetResults() []*CommandResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgFinalizeBatch)(nil), "cosmosorderbook.batch.v1.MsgFinalizeBatch")
	proto.RegisterType((*MsgFinalizeBatchResponse)(nil), "cosmosorderbook.batch.v1.MsgFinalizeBatchResponse")
}

func init() { proto.RegisterFile("cosmosorderbook/batch/v1/tx.proto", fileDescriptor_2570430717ff18c0) }

var fileDescriptor_2570430717ff18c0 = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x6b, 0x13, 0x41,
	0x18, 0xc6, 0xb3, 0x4d, 0xb5, 0xed, 0xb4, 0x8a, 0x2c, 0x45, 0xa7, 0x7b, 0x58, 0xd2, 0x22, 0x18,
	0x02, 0xd9, 0x6d, 0xe2, 0x9f, 0x83, 0x78, 0x69, 0x82, 0x82, 0x87, 0x7a, 0xd8, 0xde, 0x04, 0x09,
	0xfb, 0xe7, 0x65, 0x76, 0xb0, 0x33, 0xb3, 0xcc, 0x3b, 0x1b, 0x52, 0x41, 0x28, 0x7e, 0x02, 0x3f,
	0x89, 0xf4, 0xe0, 0x87, 0xf0, 0x58, 0x3c, 0x79, 0x94, 0xe4, 0xd0, 0xaf, 0x21, 0x99, 0xdd, 0xb4,
	0x18, 0x0d, 0x7a, 0x7c, 0xe7, 0xf9, 0x3d, 0xf3, 0xce, 0xf3, 0xce, 0x4b, 0xf6, 0x53, 0x85, 0x42,
	0xa1, 0xd2, 0x19, 0xe8, 0x44, 0xa9, 0xf7, 0x61, 0x12, 0x9b, 0x34, 0x0f, 0xc7, 0xbd, 0xd0, 0x4c,
	0x82, 0x42, 0x2b, 0xa3, 0x5c, 0xba, 0x84, 0x04, 0x16, 0x09, 0xc6, 0x3d, 0xef, 0x41, 0xa5, 0x84,
	0x02, 0xd9, 0xdc, 0x21, 0x90, 0x55, 0x16, 0x6f, 0xaf, 0x12, 0x46, 0xb6, 0x0a, 0xab, 0xa2, 0x96,
	0x1e, 0xae, 0x6e, 0x78, 0x56, 0x40, 0x4d, 0x1d, 0x9c, 0xaf, 0x91, 0x7b, 0xc7, 0xc8, 0x5e, 0x71,
	0x19, 0x9f, 0xf2, 0x0f, 0x30, 0x98, 0x33, 0xee, 0x33, 0xb2, 0x85, 0x65, 0x22, 0xb8, 0x31, 0xa0,
	0xa9, 0xd3, 0x72, 0xda, 0x5b, 0x03, 0xfa, 0xfd, 0x6b, 0x77, 0xb7, 0xbe, 0xff, 0x28, 0xcb, 0x34,
	0x20, 0x9e, 0x18, 0xcd, 0x25, 0x8b, 0x6e, 0x50, 0x77, 0x9f, 0xec, 0xd8, 0x26, 0x23, 0x59, 0x8a,
	0x04, 0x34, 0x5d, 0x6b, 0x39, 0xed, 0xf5, 0x68, 0xdb, 0x9e, 0xbd, 0xb1, 0x47, 0xee, 0x0b, 0xe2,
	0xc1, 0xa4, 0x80, 0xd4, 0x40, 0x36, 0x82, 0x49, 0x9a, 0xc7, 0x92, 0xc1, 0x48, 0xc3, 0x98, 0x23,
	0x57, 0x92, 0x36, 0xad, 0x81, 0x2e, 0x88, 0x97, 0x35, 0x10, 0xd5, 0xba, 0x3b, 0x24, 0x9b, 0xa9,
	0x12, 0x22, 0x96, 0x19, 0xd2, 0xf5, 0x56, 0xb3, 0xbd, 0xdd, 0x7f, 0x14, 0xac, 0x1a, 0x5a, 0x70,
	0xc2, 0x99, 0x84, 0x6c, 0x58, 0xf1, 0xd1, 0xb5, 0xf1, 0xf9, 0xdd, 0x4f, 0x57, 0x17, 0x9d, 0x9b,
	0x57, 0x1f, 0x7c, 0x71, 0x08, 0x5d, 0x1e, 0x41, 0x04, 0x58, 0x28, 0x89, 0xe0, 0xee, 0x91, 0xcd,
	0x2a, 0x12, 0xcf, 0xec, 0x24, 0x76, 0xa2, 0x0d, 0x5b, 0xbf, 0xce, 0xdc, 0x27, 0xe4, 0x7e, 0xa1,
	0xd0, 0xfc, 0x25, 0x46, 0x95, 0x7b, 0x77, 0xae, 0xfe, 0x11, 0xe1, 0x88, 0x6c, 0x68, 0xc0, 0xf2,
	0xd4, 0x20, 0x6d, 0xfe, 0x2b, 0xc1, 0xe2, 0xed, 0x96, 0x8f, 0x16, 0xbe, 0xfe, 0x47, 0xd2, 0x3c,
	0x46, 0xe6, 0x2a, 0x72, 0xe7, 0xf7, 0x6f, 0xeb, 0xac, 0xbe, 0x69, 0x39, 0x9f, 0xd7, 0xff, 0x7f,
	0x76, 0x31, 0x0b, 0xef, 0xd6, 0xf9, 0xd5, 0x45, 0xc7, 0x19, 0xbc, 0xfb, 0x36, 0xf5, 0x9d, 0xcb,
	0xa9, 0xef, 0xfc, 0x9c, 0xfa, 0xce, 0xe7, 0x99, 0xdf, 0xb8, 0x9c, 0xf9, 0x8d, 0x1f, 0x33, 0xbf,
	0xf1, 0x76, 0xc8, 0xb8, 0xc9, 0xcb, 0x24, 0x48, 0x95, 0x08, 0xe3, 0xb3, 0x12, 0x73, 0xc1, 0x31,
	0xd7, 0x71, 0xff, 0xf0, 0xf0, 0x69, 0xbd, 0x9b, 0xdd, 0xeb, 0x7e, 0x5d, 0x90, 0x8c, 0x4b, 0x08,
	0x27, 0xf5, 0x5e, 0xda, 0xa5, 0x0c, 0xc7, 0xbd, 0xe4, 0xb6, 0x5d, 0xcc, 0xc7, 0xbf, 0x06, 0x00,
	0x47, 0x2f, 0x68, 0x70, 0x31, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	FinalizeBatch(ctx context.Context, in *MsgFinalizeBatch, opts ...grpc.CallOption) (*MsgFinalizeBatchResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) FinalizeBatch(ctx context.Context, in *MsgFinalizeBatch, opts ...grpc.CallOption) (*MsgFinalizeBatchResponse, error) {
	out := new(MsgFinalizeBatchResponse)
	err := c.cc.Invoke(ctx, "/cosmosorderbook.batch.v1.Msg/FinalizeBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	FinalizeBatch(context.Context, *MsgFinalizeBatch) (*MsgFinalizeBatchResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) FinalizeBatch(ctx context.Context, req *MsgFinalizeBatch) (*MsgFinalizeBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeBatch not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_FinalizeBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgFinalizeBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).FinalizeBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmosorderbook.batch.v1.Msg/FinalizeBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).FinalizeBatch(ctx, req.(*MsgFinalizeBatch))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmosorderbook.batch.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FinalizeBatch",
			Handler:    _Msg_FinalizeBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmosorderbook/batch/v1/tx.proto",
}

func (m *MsgFinalizeBatch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFinalizeBatch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFinalizeBatch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Commands) > 0 {
		for iNdEx := len(m.Commands) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Commands[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.ExpectedExchangeRevision != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ExpectedExchangeRevision))
		i--
		dAtA[i] = 0x18
	}
	if m.BatchNumber != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BatchNumber))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Submitter) > 0 {
		i -= len(m.Submitter)
		copy(dAtA[i:], m.Submitter)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Submitter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgFinalizeBatchResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFinalizeBatchResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFinalizeBatchResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Results) > 0 {
		for iNdEx := len(m.Results) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Results[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.PostExchangeRevision != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PostExchangeRevision))
		i--
		dAtA[i] = 0x10
	}
	if len(m.BatchId) > 0 {
		i -= len(m.BatchId)
		copy(dAtA[i:], m.BatchId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BatchId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgFinalizeBatch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Submitter)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.BatchNumber != 0 {
		n += 1 + sovTx(uint64(m.BatchNumber))
	}
	if m.ExpectedExchangeRevision != 0 {
		n += 1 + sovTx(uint64(m.ExpectedExchangeRevision))
	}
	if len(m.Commands) > 0 {
		for _, e := range m.Commands {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgFinalizeBatchResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BatchId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PostExchangeRevision != 0 {
		n += 1 + sovTx(uint64(m.PostExchangeRevision))
	}
	if len(m.Results) > 0 {
		for _, e := range m.Results {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgFinalizeBatch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFinalizeBatch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFinalizeBatch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Submitter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Submitter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchNumber", wireType)
			}
			m.BatchNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BatchNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpectedExchangeRevision", wireType)
			}
			m.ExpectedExchangeRevision = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpectedExchangeRevision |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commands", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Commands = append(m.Commands, &SignedCommand{})
			if err := m.Commands[len(m.Commands)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFinalizeBatchResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFinalizeBatchResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFinalizeBatchResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BatchId = append(m.BatchId[:0], dAtA[iNdEx:postIndex]...)
			if m.BatchId == nil {
				m.BatchId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostExchangeRevision", wireType)
			}
			m.PostExchangeRevision = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PostExchangeRevision |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Results", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Results = append(m.Results, &CommandResult{})
			if err := m.Results[len(m.Results)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
