// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmosorderbook/batch/v1/types.proto

package v1

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// CommandType matches the canonical command discriminator.
type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED  CommandType = 0
	CommandType_COMMAND_TYPE_PLACE_ORDER  CommandType = 1
	CommandType_COMMAND_TYPE_CANCEL_ORDER CommandType = 2
)

var CommandType_name = map[int32]string{
	0: "COMMAND_TYPE_UNSPECIFIED",
	1: "COMMAND_TYPE_PLACE_ORDER",
	2: "COMMAND_TYPE_CANCEL_ORDER",
}

var CommandType_value = map[string]int32{
	"COMMAND_TYPE_UNSPECIFIED":  0,
	"COMMAND_TYPE_PLACE_ORDER":  1,
	"COMMAND_TYPE_CANCEL_ORDER": 2,
}

func (x CommandType) String() string {
	return proto.EnumName(CommandType_name, int32(x))
}

func (CommandType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fa23a3b5dea6cfc2, []int{0}
}

// Side matches pkg/domain.
type Side int32

const (
	Side_SIDE_UNSPECIFIED Side = 0
	Side_SIDE_BUY         Side = 1
	Side_SIDE_SELL        Side = 2
)

var Side_name = map[int32]string{
	0: "SIDE_UNSPECIFIED",
	1: "SIDE_BUY",
	2: "SIDE_SELL",
}

var Side_value = map[string]int32{
	"SIDE_UNSPECIFIED": 0,
	"SIDE_BUY":         1,
	"SIDE_SELL":        2,
}

func (x Side) String() string {
	return proto.EnumName(Side_name, int32(x))
}

func (Side) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fa23a3b5dea6cfc2, []int{1}
}

// OrderType matches pkg/domain.
type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_ORDER_TYPE_LIMIT       OrderType = 1
	OrderType_ORDER_TYPE_MARKET      OrderType = 2
)

var OrderType_name = map[int32]string{
	0: "ORDER_TYPE_UNSPECIFIED",
	1: "ORDER_TYPE_LIMIT",
	2: "ORDER_TYPE_MARKET",
}

var OrderType_value = map[string]int32{
	"ORDER_TYPE_UNSPECIFIED": 0,
	"ORDER_TYPE_LIMIT":       1,
	"ORDER_TYPE_MARKET":      2,
}

func (x OrderType) String() string {
	return proto.EnumName(OrderType_name, int32(x))
}

func (OrderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fa23a3b5dea6cfc2, []int{2}
}

// TimeInForce matches pkg/domain.
type TimeInForce int32

const (
	TimeInForce_TIME_IN_FORCE_UNSPECIFIED TimeInForce = 0
	TimeInForce_TIME_IN_FORCE_GTC         TimeInForce = 1
	TimeInForce_TIME_IN_FORCE_IOC         TimeInForce = 2
	TimeInForce_TIME_IN_FORCE_FOK         TimeInForce = 3
	TimeInForce_TIME_IN_FORCE_GTD         TimeInForce = 4
)

var TimeInForce_name = map[int32]string{
	0: "TIME_IN_FORCE_UNSPECIFIED",
	1: "TIME_IN_FORCE_GTC",
	2: "TIME_IN_FORCE_IOC",
	3: "TIME_IN_FORCE_FOK",
	4: "TIME_IN_FORCE_GTD",
}

var TimeInForce_value = map[string]int32{
	"TIME_IN_FORCE_UNSPECIFIED": 0,
	"TIME_IN_FORCE_GTC":         1,
	"TIME_IN_FORCE_IOC":         2,
	"TIME_IN_FORCE_FOK":         3,
	"TIME_IN_FORCE_GTD":         4,
}

func (x TimeInForce) String() string {
	return proto.EnumName(TimeInForce_name, int32(x))
}

func (TimeInForce) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fa23a3b5dea6cfc2, []int{3}
}

// OrderStatus is the outcome of one successful command.
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_RESTING     OrderStatus = 1
	OrderStatus_ORDER_STATUS_FILLED      OrderStatus = 2
	OrderStatus_ORDER_STATUS_CANCELLED   OrderStatus = 3
	OrderStatus_ORDER_STATUS_UNFILLED    OrderStatus = 4
)

var OrderStatus_name = map[int32]string{
	0: "ORDER_STATUS_UNSPECIFIED",
	1: "ORDER_STATUS_RESTING",
	2: "ORDER_STATUS_FILLED",
	3: "ORDER_STATUS_CANCELLED",
	4: "ORDER_STATUS_UNFILLED",
}

var OrderStatus_value = map[string]int32{
	"ORDER_STATUS_UNSPECIFIED": 0,
	"ORDER_STATUS_RESTING":     1,
	"ORDER_STATUS_FILLED":      2,
	"ORDER_STATUS_CANCELLED":   3,
	"ORDER_STATUS_UNFILLED":    4,
}

func (x OrderStatus) String() string {
	return proto.EnumName(OrderStatus_name, int32(x))
}

func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fa23a3b5dea6cfc2, []int{4}
}

// Place is one place-order body. The order ID is derived by the exchange.
type Place struct {
	MarketId             uint64      `protobuf:"varint,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Side                 Side        `protobuf:"varint,2,opt,name=side,proto3,enum=cosmosorderbook.batch.v1.Side" json:"side,omitempty"`
	OrderType            OrderType   `protobuf:"varint,3,opt,name=order_type,json=orderType,proto3,enum=cosmosorderbook.batch.v1.OrderType" json:"order_type,omitempty"`
	TimeInForce          TimeInForce `protobuf:"varint,4,opt,name=time_in_force,json=timeInForce,proto3,enum=cosmosorderbook.batch.v1.TimeInForce" json:"time_in_force,omitempty"`
	QuantityLots         uint64      `protobuf:"varint,5,opt,name=quantity_lots,json=quantityLots,proto3" json:"quantity_lots,omitempty"`
	PriceTicks           uint64      `protobuf:"varint,6,opt,name=price_ticks,json=priceTicks,proto3" json:"price_ticks,omitempty"`
	ExpiryHeight         uint64      `protobuf:"varint,7,opt,name=expiry_height,json=expiryHeight,proto3" json:"expiry_height,omitempty"`
	ClientOrderId        []byte      `protobuf:"bytes,8,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Place) Reset()         { *m = Place{} }
func (m *Place) String() string { return proto.CompactTextString(m) }
func (*Place) ProtoMessage()    {}
func (*Place) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa23a3b5dea6cfc2, []int{0}
}
func (m *Place) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Place.Unmarshal(m, b)
}
func (m *Place) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Place.Marshal(b, m, deterministic)
}
func (m *Place) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Place.Merge(m, src)
}
func (m *Place) XXX_Size() int {
	return xxx_messageInfo_Place.Size(m)
}
func (m *Place) XXX_DiscardUnknown() {
	xxx_messageInfo_Place.DiscardUnknown(m)
}

var xxx_messageInfo_Place proto.InternalMessageInfo

func (m *Place) GetMarketId() uint64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *Place) GetSide() Side {
	if m != nil {
		return m.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (m *Place) GetOrderType() OrderType {
	if m != nil {
		return m.OrderType
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (m *Place) GetTimeInForce() TimeInForce {
	if m != nil {
		return m.TimeInForce
	}
	return TimeInForce_TIME_IN_FORCE_UNSPECIFIED
}

func (m *Place) GetQuantityLots() uint64 {
	if m != nil {
		return m.QuantityLots
	}
	return 0
}

func (m *Place) GetPriceTicks() uint64 {
	if m != nil {
		return m.PriceTicks
	}
	return 0
}

func (m *Place) GetExpiryHeight() uint64 {
	if m != nil {
		return m.ExpiryHeight
	}
	return 0
}

func (m *Place) GetClientOrderId() []byte {
	if m != nil {
		return m.ClientOrderId
	}
	return nil
}

// Cancel names one live order.
type Cancel struct {
	OrderId              []byte   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cancel) Reset()         { *m = Cancel{} }
func (m *Cancel) String() string { return proto.CompactTextString(m) }
func (*Cancel) ProtoMessage()    {}
func (*Cancel) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa23a3b5dea6cfc2, []int{1}
}
func (m *Cancel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cancel.Unmarshal(m, b)
}
func (m *Cancel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cancel.Marshal(b, m, deterministic)
}
func (m *Cancel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cancel.Merge(m, src)
}
func (m *Cancel) XXX_Size() int {
	return xxx_messageInfo_Cancel.Size(m)
}
func (m *Cancel) XXX_DiscardUnknown() {
	xxx_messageInfo_Cancel.DiscardUnknown(m)
}

var xxx_messageInfo_Cancel proto.InternalMessageInfo

func (m *Cancel) GetOrderId() []byte {
	if m != nil {
		return m.OrderId
	}
	return nil
}

// SignedCommand is one trader command inside a batch.
// The signature covers canonical bytes, not this protobuf encoding.
type SignedCommand struct {
	ProtocolVersion      uint32      `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ChainId              string      `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ExchangeInstanceId   []byte      `protobuf:"bytes,3,opt,name=exchange_instance_id,json=exchangeInstanceId,proto3" json:"exchange_instance_id,omitempty"`
	Owner                string      `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	CommandNonce         uint64      `protobuf:"varint,5,opt,name=command_nonce,json=commandNonce,proto3" json:"command_nonce,omitempty"`
	CommandType          CommandType `protobuf:"varint,6,opt,name=command_type,json=commandType,proto3,enum=cosmosorderbook.batch.v1.CommandType" json:"command_type,omitempty"`
	Place                *Place      `protobuf:"bytes,7,opt,name=place,proto3" json:"place,omitempty"`
	Cancel               *Cancel     `protobuf:"bytes,8,opt,name=cancel,proto3" json:"cancel,omitempty"`
	PubKey               []byte      `protobuf:"bytes,9,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Signature            []byte      `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SignedCommand) Reset()         { *m = SignedCommand{} }
func (m *SignedCommand) String() string { return proto.CompactTextString(m) }
func (*SignedCommand) ProtoMessage()    {}
func (*SignedCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa23a3b5dea6cfc2, []int{2}
}
func (m *SignedCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedCommand.Unmarshal(m, b)
}
func (m *SignedCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedCommand.Marshal(b, m, deterministic)
}
func (m *SignedCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedCommand.Merge(m, src)
}
func (m *SignedCommand) XXX_Size() int {
	return xxx_messageInfo_SignedCommand.Size(m)
}
func (m *SignedCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedCommand.DiscardUnknown(m)
}

var xxx_messageInfo_SignedCommand proto.InternalMessageInfo

func (m *SignedCommand) GetProtocolVersion() uint32 {
	if m != nil {
		return m.ProtocolVersion
	}
	return 0
}

func (m *SignedCommand) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *SignedCommand) GetExchangeInstanceId() []byte {
	if m != nil {
		return m.ExchangeInstanceId
	}
	return nil
}

func (m *SignedCommand) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *SignedCommand) GetCommandNonce() uint64 {
	if m != nil {
		return m.CommandNonce
	}
	return 0
}

func (m *SignedCommand) GetCommandType() CommandType {
	if m != nil {
		return m.CommandType
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (m *SignedCommand) GetPlace() *Place {
	if m != nil {
		return m.Place
	}
	return nil
}

func (m *SignedCommand) GetCancel() *Cancel {
	if m != nil {
		return m.Cancel
	}
	return nil
}

func (m *SignedCommand) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *SignedCommand) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// TradeRef identifies one fill without copying the trade record.
type TradeRef struct {
	MarketId             uint64   `protobuf:"varint,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Sequence             uint64   `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradeRef) Reset()         { *m = TradeRef{} }
func (m *TradeRef) String() string { return proto.CompactTextString(m) }
func (*TradeRef) ProtoMessage()    {}
func (*TradeRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa23a3b5dea6cfc2, []int{3}
}
func (m *TradeRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeRef.Unmarshal(m, b)
}
func (m *TradeRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeRef.Marshal(b, m, deterministic)
}
func (m *TradeRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeRef.Merge(m, src)
}
func (m *TradeRef) XXX_Size() int {
	return xxx_messageInfo_TradeRef.Size(m)
}
func (m *TradeRef) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeRef.DiscardUnknown(m)
}

var xxx_messageInfo_TradeRef proto.InternalMessageInfo

func (m *TradeRef) GetMarketId() uint64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *TradeRef) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

// CommandResult is the summary stored for one successful command.
type CommandResult struct {
	Index                uint32      `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	CommandType          CommandType `protobuf:"varint,2,opt,name=command_type,json=commandType,proto3,enum=cosmosorderbook.batch.v1.CommandType" json:"command_type,omitempty"`
	Owner                string      `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	OrderId              []byte      `protobuf:"bytes,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status               OrderStatus `protobuf:"varint,5,opt,name=status,proto3,enum=cosmosorderbook.batch.v1.OrderStatus" json:"status,omitempty"`
	RemainingLots        uint64      `protobuf:"varint,6,opt,name=remaining_lots,json=remainingLots,proto3" json:"remaining_lots,omitempty"`
	Trades               []*TradeRef `protobuf:"bytes,7,rep,name=trades,proto3" json:"trades,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CommandResult) Reset()         { *m = CommandResult{} }
func (m *CommandResult) String() string { return proto.CompactTextString(m) }
func (*CommandResult) ProtoMessage()    {}
func (*CommandResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa23a3b5dea6cfc2, []int{4}
}
func (m *CommandResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandResult.Unmarshal(m, b)
}
func (m *CommandResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandResult.Marshal(b, m, deterministic)
}
func (m *CommandResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandResult.Merge(m, src)
}
func (m *CommandResult) XXX_Size() int {
	return xxx_messageInfo_CommandResult.Size(m)
}
func (m *CommandResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandResult.DiscardUnknown(m)
}

var xxx_messageInfo_CommandResult proto.InternalMessageInfo

func (m *CommandResult) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *CommandResult) GetCommandType() CommandType {
	if m != nil {
		return m.CommandType
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (m *CommandResult) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *CommandResult) GetOrderId() []byte {
	if m != nil {
		return m.OrderId
	}
	return nil
}

func (m *CommandResult) GetStatus() OrderStatus {
	if m != nil {
		return m.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (m *CommandResult) GetRemainingLots() uint64 {
	if m != nil {
		return m.RemainingLots
	}
	return 0
}

func (m *CommandResult) GetTrades() []*TradeRef {
	if m != nil {
		return m.Trades
	}
	return nil
}

// Batch is one finalized batch record.
// BatchCommitment binds this batch to the previous commitment and ResultsHash.
// It is not an exchange state root.
type Batch struct {
	BatchNumber             uint64           `protobuf:"varint,1,opt,name=batch_number,json=batchNumber,proto3" json:"batch_number,omitempty"`
	BatchId                 []byte           `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	ExecutionHeight         uint64           `protobuf:"varint,3,opt,name=execution_height,json=executionHeight,proto3" json:"execution_height,omitempty"`
	PreExchangeRevision     uint64           `protobuf:"varint,4,opt,name=pre_exchange_revision,json=preExchangeRevision,proto3" json:"pre_exchange_revision,omitempty"`
	PostExchangeRevision    uint64           `protobuf:"varint,5,opt,name=post_exchange_revision,json=postExchangeRevision,proto3" json:"post_exchange_revision,omitempty"`
	Results                 []*CommandResult `protobuf:"bytes,6,rep,name=results,proto3" json:"results,omitempty"`
	PreviousBatchCommitment []byte           `protobuf:"bytes,7,opt,name=previous_batch_commitment,json=previousBatchCommitment,proto3" json:"previous_batch_commitment,omitempty"`
	BatchCommitment         []byte           `protobuf:"bytes,8,opt,name=batch_commitment,json=batchCommitment,proto3" json:"batch_commitment,omitempty"`
	ResultsHash             []byte           `protobuf:"bytes,9,opt,name=results_hash,json=resultsHash,proto3" json:"results_hash,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}         `json:"-"`
	XXX_unrecognized        []byte           `json:"-"`
	XXX_sizecache           int32            `json:"-"`
}

func (m *Batch) Reset()         { *m = Batch{} }
func (m *Batch) String() string { return proto.CompactTextString(m) }
func (*Batch) ProtoMessage()    {}
func (*Batch) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa23a3b5dea6cfc2, []int{5}
}
func (m *Batch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Batch.Unmarshal(m, b)
}
func (m *Batch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Batch.Marshal(b, m, deterministic)
}
func (m *Batch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Batch.Merge(m, src)
}
func (m *Batch) XXX_Size() int {
	return xxx_messageInfo_Batch.Size(m)
}
func (m *Batch) XXX_DiscardUnknown() {
	xxx_messageInfo_Batch.DiscardUnknown(m)
}

var xxx_messageInfo_Batch proto.InternalMessageInfo

func (m *Batch) GetBatchNumber() uint64 {
	if m != nil {
		return m.BatchNumber
	}
	return 0
}

func (m *Batch) GetBatchId() []byte {
	if m != nil {
		return m.BatchId
	}
	return nil
}

func (m *Batch) GetExecutionHeight() uint64 {
	if m != nil {
		return m.ExecutionHeight
	}
	return 0
}

func (m *Batch) GetPreExchangeRevision() uint64 {
	if m != nil {
		return m.PreExchangeRevision
	}
	return 0
}

func (m *Batch) GetPostExchangeRevision() uint64 {
	if m != nil {
		return m.PostExchangeRevision
	}
	return 0
}

func (m *Batch) GetResults() []*CommandResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *Batch) GetPreviousBatchCommitment() []byte {
	if m != nil {
		return m.PreviousBatchCommitment
	}
	return nil
}

func (m *Batch) GetBatchCommitment() []byte {
	if m != nil {
		return m.BatchCommitment
	}
	return nil
}

func (m *Batch) GetResultsHash() []byte {
	if m != nil {
		return m.ResultsHash
	}
	return nil
}

func init() {
	proto.RegisterEnum("cosmosorderbook.batch.v1.CommandType", CommandType_name, CommandType_value)
	proto.RegisterEnum("cosmosorderbook.batch.v1.Side", Side_name, Side_value)
	proto.RegisterEnum("cosmosorderbook.batch.v1.OrderType", OrderType_name, OrderType_value)
	proto.RegisterEnum("cosmosorderbook.batch.v1.TimeInForce", TimeInForce_name, TimeInForce_value)
	proto.RegisterEnum("cosmosorderbook.batch.v1.OrderStatus", OrderStatus_name, OrderStatus_value)
	proto.RegisterType((*Place)(nil), "cosmosorderbook.batch.v1.Place")
	proto.RegisterType((*Cancel)(nil), "cosmosorderbook.batch.v1.Cancel")
	proto.RegisterType((*SignedCommand)(nil), "cosmosorderbook.batch.v1.SignedCommand")
	proto.RegisterType((*TradeRef)(nil), "cosmosorderbook.batch.v1.TradeRef")
	proto.RegisterType((*CommandResult)(nil), "cosmosorderbook.batch.v1.CommandResult")
	proto.RegisterType((*Batch)(nil), "cosmosorderbook.batch.v1.Batch")
}

func init() {
	proto.RegisterFile("cosmosorderbook/batch/v1/types.proto", fileDescriptor_fa23a3b5dea6cfc2)
}

var fileDescriptor_fa23a3b5dea6cfc2 = []byte{
	// 1090 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdd, 0x72, 0xda, 0x46,
	0x14, 0xae, 0x00, 0xf3, 0x73, 0x80, 0x58, 0xd9, 0xe0, 0x44, 0x4e, 0xd3, 0xc6, 0x21, 0x4d, 0xeb,
	0x7a, 0x26, 0x90, 0xd0, 0x66, 0xa6, 0xcd, 0x4c, 0x2f, 0xb0, 0x90, 0x13, 0x8d, 0x31, 0x78, 0x16,
	0xb9, 0x33, 0xe9, 0x8d, 0x46, 0x48, 0x1b, 0xb4, 0x63, 0x90, 0x14, 0x69, 0xe5, 0x9a, 0x37, 0xe8,
	0x0b, 0xf4, 0x19, 0xfa, 0x02, 0x7d, 0x82, 0x3e, 0x56, 0xaf, 0x3a, 0xbb, 0x2b, 0x30, 0x06, 0xdb,
	0x99, 0xe9, 0x1d, 0xe7, 0xfb, 0xbe, 0x73, 0x76, 0xf5, 0x9d, 0x73, 0x24, 0xe0, 0x1b, 0x37, 0x4c,
	0x66, 0x61, 0x12, 0xc6, 0x1e, 0x89, 0xc7, 0x61, 0x78, 0xde, 0x1e, 0x3b, 0xcc, 0xf5, 0xdb, 0x17,
	0xaf, 0xdb, 0x6c, 0x1e, 0x91, 0xa4, 0x15, 0xc5, 0x21, 0x0b, 0x91, 0xb6, 0xa6, 0x6a, 0x09, 0x55,
	0xeb, 0xe2, 0x75, 0xf3, 0xdf, 0x1c, 0x6c, 0x9d, 0x4e, 0x1d, 0x97, 0xa0, 0x2f, 0xa1, 0x32, 0x73,
	0xe2, 0x73, 0xc2, 0x6c, 0xea, 0x69, 0xca, 0x9e, 0xb2, 0x5f, 0xc0, 0x65, 0x09, 0x98, 0x1e, 0xea,
	0x40, 0x21, 0xa1, 0x1e, 0xd1, 0x72, 0x7b, 0xca, 0xfe, 0xbd, 0xce, 0xd7, 0xad, 0xdb, 0xea, 0xb5,
	0x46, 0xd4, 0x23, 0x58, 0x68, 0xd1, 0x21, 0x80, 0x10, 0xd8, 0xfc, 0x26, 0x5a, 0x5e, 0x64, 0x3e,
	0xbf, 0x3d, 0x73, 0xc8, 0x21, 0x6b, 0x1e, 0x11, 0x5c, 0x09, 0x17, 0x3f, 0x91, 0x09, 0x75, 0x46,
	0x67, 0xc4, 0xa6, 0x81, 0xfd, 0x31, 0x8c, 0x5d, 0xa2, 0x15, 0x44, 0x99, 0x17, 0xb7, 0x97, 0xb1,
	0xe8, 0x8c, 0x98, 0xc1, 0x11, 0x17, 0xe3, 0x2a, 0xbb, 0x0a, 0xd0, 0x73, 0xa8, 0x7f, 0x4a, 0x9d,
	0x80, 0x51, 0x36, 0xb7, 0xa7, 0x21, 0x4b, 0xb4, 0x2d, 0xf1, 0x8c, 0xb5, 0x05, 0xd8, 0x0f, 0x59,
	0x82, 0x9e, 0x42, 0x35, 0x8a, 0xa9, 0x4b, 0x6c, 0x46, 0xdd, 0xf3, 0x44, 0x2b, 0x0a, 0x09, 0x08,
	0xc8, 0xe2, 0x08, 0xaf, 0x42, 0x2e, 0x23, 0x1a, 0xcf, 0x6d, 0x9f, 0xd0, 0x89, 0xcf, 0xb4, 0x92,
	0xac, 0x22, 0xc1, 0xf7, 0x02, 0x43, 0xdf, 0xc2, 0xb6, 0x3b, 0xa5, 0x24, 0x60, 0xb6, 0x34, 0x80,
	0x7a, 0x5a, 0x79, 0x4f, 0xd9, 0xaf, 0xe1, 0xba, 0x84, 0xc5, 0xa3, 0x9a, 0x5e, 0xf3, 0x39, 0x14,
	0x75, 0x27, 0x70, 0xc9, 0x14, 0xed, 0x42, 0x79, 0x29, 0x55, 0x84, 0xb4, 0x14, 0x66, 0xa2, 0xbf,
	0xf3, 0x50, 0x1f, 0xd1, 0x49, 0x40, 0x3c, 0x3d, 0x9c, 0xcd, 0x9c, 0xc0, 0x43, 0xdf, 0x83, 0x2a,
	0xda, 0xea, 0x86, 0x53, 0xfb, 0x82, 0xc4, 0x09, 0x0d, 0x03, 0x91, 0x54, 0xc7, 0xdb, 0x0b, 0xfc,
	0x57, 0x09, 0xf3, 0xba, 0xae, 0xef, 0xd0, 0x80, 0xd7, 0xe5, 0xbd, 0xab, 0xe0, 0x92, 0x88, 0x4d,
	0x0f, 0xbd, 0x82, 0x06, 0xb9, 0x74, 0x7d, 0x27, 0x98, 0x70, 0x7b, 0x13, 0xc6, 0x2f, 0xc2, 0x65,
	0x79, 0x71, 0x3c, 0x5a, 0x70, 0x66, 0x46, 0x99, 0x1e, 0x6a, 0xc0, 0x56, 0xf8, 0x7b, 0x40, 0x62,
	0xd1, 0x84, 0x0a, 0x96, 0x01, 0x77, 0xc4, 0x95, 0x17, 0xb3, 0x83, 0x30, 0x70, 0xc9, 0xc2, 0xd7,
	0x0c, 0x1c, 0x70, 0x0c, 0xbd, 0x87, 0x45, 0x2c, 0xa7, 0xa1, 0xf8, 0xb9, 0x36, 0x66, 0xcf, 0x2a,
	0xe6, 0xa1, 0xea, 0x5e, 0x05, 0xe8, 0x0d, 0x6c, 0x45, 0x7c, 0x5e, 0x85, 0xf1, 0xd5, 0xce, 0xd3,
	0xdb, 0x4b, 0x88, 0xb1, 0xc6, 0x52, 0x8d, 0x7e, 0x82, 0xa2, 0x2b, 0xac, 0x16, 0x9d, 0xa8, 0x76,
	0xf6, 0xee, 0x38, 0x5a, 0xe8, 0x70, 0xa6, 0x47, 0x8f, 0xa0, 0x14, 0xa5, 0x63, 0xfb, 0x9c, 0xcc,
	0xb5, 0x8a, 0xb0, 0xa6, 0x18, 0xa5, 0xe3, 0x63, 0x32, 0x47, 0x4f, 0xa0, 0x92, 0xd0, 0x49, 0xe0,
	0xb0, 0x34, 0x26, 0x1a, 0x08, 0xea, 0x0a, 0x68, 0xea, 0x50, 0xb6, 0x62, 0xc7, 0x23, 0x98, 0x7c,
	0xbc, 0x7b, 0xb5, 0x1e, 0x43, 0x39, 0x21, 0x9f, 0x52, 0xc2, 0xad, 0xcb, 0x49, 0x6e, 0x11, 0x37,
	0xff, 0xc9, 0x41, 0x3d, 0x73, 0x02, 0x93, 0x24, 0x9d, 0x32, 0xde, 0x03, 0x1a, 0x78, 0xe4, 0x32,
	0x6b, 0xb8, 0x0c, 0x36, 0xec, 0xcd, 0xfd, 0x6f, 0x7b, 0x97, 0x3d, 0xce, 0xaf, 0xf6, 0x78, 0x75,
	0x3c, 0x0b, 0xd7, 0xc6, 0x13, 0xfd, 0x02, 0xc5, 0x84, 0x39, 0x2c, 0x95, 0xfb, 0x74, 0xe7, 0xa1,
	0x62, 0xec, 0x47, 0x42, 0x8c, 0xb3, 0x24, 0xf4, 0x02, 0xee, 0xc5, 0x64, 0xe6, 0xd0, 0x80, 0x06,
	0x13, 0xb9, 0x96, 0x72, 0xe7, 0xea, 0x4b, 0x54, 0xec, 0xe5, 0x5b, 0x28, 0x32, 0xee, 0x66, 0xa2,
	0x95, 0xf6, 0xf2, 0xfb, 0xd5, 0x4e, 0xf3, 0x8e, 0x17, 0x40, 0xe6, 0x3a, 0xce, 0x32, 0x9a, 0x7f,
	0xe5, 0x61, 0xeb, 0x90, 0xb3, 0xe8, 0x19, 0xd4, 0x84, 0xcc, 0x0e, 0xd2, 0xd9, 0x98, 0xc4, 0x59,
	0x2b, 0xaa, 0x02, 0x1b, 0x08, 0x88, 0x3f, 0xa9, 0x94, 0x64, 0x0b, 0x53, 0xc3, 0x25, 0x11, 0x9b,
	0x62, 0xed, 0xc8, 0x25, 0x71, 0x53, 0x46, 0xc3, 0x60, 0xb1, 0xfd, 0x79, 0x51, 0x61, 0x7b, 0x89,
	0x67, 0x2f, 0x80, 0x0e, 0xec, 0x44, 0x31, 0xb1, 0x97, 0xfb, 0x15, 0x93, 0x0b, 0x2a, 0xd6, 0xb4,
	0x20, 0xf4, 0x0f, 0xa2, 0x98, 0x18, 0x19, 0x87, 0x33, 0x0a, 0xfd, 0x08, 0x0f, 0xa3, 0x30, 0x61,
	0x37, 0x24, 0xc9, 0x85, 0x6a, 0x70, 0x76, 0x23, 0xab, 0x0b, 0xa5, 0x58, 0x4c, 0x06, 0x37, 0x8e,
	0x3b, 0xf3, 0xdd, 0x67, 0x9b, 0x2e, 0x27, 0x09, 0x2f, 0xf2, 0xd0, 0x5b, 0xd8, 0x8d, 0xf8, 0x59,
	0x61, 0x9a, 0xd8, 0xf2, 0xd9, 0xf9, 0x40, 0x50, 0x36, 0x23, 0x81, 0x7c, 0xbd, 0xd5, 0xf0, 0xa3,
	0x85, 0x40, 0xf8, 0xa8, 0x2f, 0x69, 0xee, 0xc9, 0x46, 0x8a, 0x7c, 0xd5, 0x6d, 0x8f, 0xd7, 0xa4,
	0xcf, 0xa0, 0x96, 0x9d, 0x68, 0xfb, 0x4e, 0xe2, 0x67, 0xcb, 0x54, 0xcd, 0xb0, 0xf7, 0x4e, 0xe2,
	0x1f, 0xf8, 0x50, 0x5d, 0x19, 0x4c, 0xf4, 0x04, 0x34, 0x7d, 0x78, 0x72, 0xd2, 0x1d, 0xf4, 0x6c,
	0xeb, 0xc3, 0xa9, 0x61, 0x9f, 0x0d, 0x46, 0xa7, 0x86, 0x6e, 0x1e, 0x99, 0x46, 0x4f, 0xfd, 0x62,
	0x83, 0x3d, 0xed, 0x77, 0x75, 0xc3, 0x1e, 0xe2, 0x9e, 0x81, 0x55, 0x05, 0x7d, 0x05, 0xbb, 0xd7,
	0x58, 0xbd, 0x3b, 0xd0, 0x8d, 0x7e, 0x46, 0xe7, 0x0e, 0x7e, 0x86, 0x02, 0xff, 0x52, 0xa1, 0x06,
	0xa8, 0x23, 0xb3, 0xb7, 0x5e, 0xba, 0x06, 0x65, 0x81, 0x1e, 0x9e, 0x7d, 0x50, 0x15, 0x54, 0x87,
	0x8a, 0x88, 0x46, 0x46, 0xbf, 0xaf, 0xe6, 0x0e, 0x2c, 0xa8, 0x2c, 0x3f, 0x55, 0xe8, 0x31, 0x3c,
	0x14, 0x25, 0x6f, 0xba, 0x60, 0x03, 0xd4, 0x15, 0xae, 0x6f, 0x9e, 0x98, 0x96, 0xaa, 0xa0, 0x1d,
	0xb8, 0xbf, 0x82, 0x9e, 0x74, 0xf1, 0xb1, 0x61, 0xa9, 0xb9, 0x83, 0x3f, 0x14, 0xa8, 0xae, 0x7c,
	0xba, 0xf8, 0xfd, 0x2d, 0xf3, 0xc4, 0xb0, 0xcd, 0x81, 0x7d, 0x34, 0xc4, 0xfa, 0x7a, 0xed, 0x1d,
	0xb8, 0x7f, 0x9d, 0x7e, 0x67, 0xe9, 0xaa, 0xb2, 0x09, 0x9b, 0x43, 0x5d, 0xcd, 0x6d, 0xc2, 0x47,
	0xc3, 0x63, 0x35, 0x7f, 0x53, 0x91, 0x9e, 0x5a, 0x38, 0xf8, 0x53, 0x81, 0xea, 0xca, 0xaa, 0x72,
	0xa3, 0xe5, 0x8d, 0x47, 0x56, 0xd7, 0x3a, 0x1b, 0xad, 0xdd, 0x44, 0x83, 0xc6, 0x35, 0x16, 0x1b,
	0x23, 0xcb, 0x1c, 0xbc, 0x53, 0x15, 0xf4, 0x08, 0x1e, 0x5c, 0x63, 0x8e, 0xcc, 0x7e, 0xdf, 0xe8,
	0xa9, 0xb9, 0x2b, 0xd3, 0x32, 0x42, 0xf6, 0x86, 0x73, 0x79, 0xb4, 0x0b, 0x3b, 0x6b, 0x87, 0x65,
	0x69, 0x85, 0x43, 0xe3, 0x37, 0x7d, 0x42, 0x99, 0x9f, 0x8e, 0x5b, 0x6e, 0x38, 0x6b, 0x3b, 0xf3,
	0x34, 0xf1, 0x67, 0x34, 0xf1, 0x63, 0xa7, 0xf3, 0xea, 0xd5, 0x9b, 0xb6, 0x9c, 0xfa, 0x97, 0xcb,
	0xb1, 0x7f, 0x49, 0x82, 0x09, 0x0d, 0x48, 0xfb, 0x32, 0xfb, 0x47, 0x24, 0xfe, 0x0e, 0xb5, 0x2f,
	0x5e, 0x8f, 0x8b, 0xe2, 0x1b, 0xf9, 0xc3, 0x7f, 0x03, 0x00, 0x2a, 0x52, 0xc9, 0x68, 0x3a, 0x09,
	0x00, 0x00,
}
