// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmosorderbook/exchange/v1/genesis.proto

package v1

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState is the exchange portion of genesis.
// Balances are accepted only when bank custody already covers them.
// Active orders are authoritative. Book, owner, client, and expiration
// indexes are rebuilt from those orders during InitGenesis.
// Trades are included so the per-market trade sequence stays aligned
// with the stored history.
type GenesisState struct {
	InstanceId           string            `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Assets               []*Asset          `protobuf:"bytes,2,rep,name=assets,proto3" json:"assets,omitempty"`
	Markets              []*Market         `protobuf:"bytes,3,rep,name=markets,proto3" json:"markets,omitempty"`
	Balances             []*GenesisBalance `protobuf:"bytes,4,rep,name=balances,proto3" json:"balances,omitempty"`
	Nonces               []*AccountNonce   `protobuf:"bytes,5,rep,name=nonces,proto3" json:"nonces,omitempty"`
	OrderSequences       []*MarketSequence `protobuf:"bytes,6,rep,name=order_sequences,json=orderSequences,proto3" json:"order_sequences,omitempty"`
	TradeSequences       []*MarketSequence `protobuf:"bytes,7,rep,name=trade_sequences,json=tradeSequences,proto3" json:"trade_sequences,omitempty"`
	Revision             uint64            `protobuf:"varint,8,opt,name=revision,proto3" json:"revision,omitempty"`
	Orders               []*GenesisOrder   `protobuf:"bytes,9,rep,name=orders,proto3" json:"orders,omitempty"`
	Trades               []*Trade          `protobuf:"bytes,10,rep,name=trades,proto3" json:"trades,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6075897526ec355, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisState.Unmarshal(m, b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return xxx_messageInfo_GenesisState.Size(m)
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *GenesisState) GetAssets() []*Asset {
	if m != nil {
		return m.Assets
	}
	return nil
}

func (m *GenesisState) GetMarkets() []*Market {
	if m != nil {
		return m.Markets
	}
	return nil
}

func (m *GenesisState) GetBalances() []*GenesisBalance {
	if m != nil {
		return m.Balances
	}
	return nil
}

func (m *GenesisState) GetNonces() []*AccountNonce {
	if m != nil {
		return m.Nonces
	}
	return nil
}

func (m *GenesisState) GetOrderSequences() []*MarketSequence {
	if m != nil {
		return m.OrderSequences
	}
	return nil
}

func (m *GenesisState) GetTradeSequences() []*MarketSequence {
	if m != nil {
		return m.TradeSequences
	}
	return nil
}

func (m *GenesisState) GetRevision() uint64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *GenesisState) GetOrders() []*GenesisOrder {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *GenesisState) GetTrades() []*Trade {
	if m != nil {
		return m.Trades
	}
	return nil
}

// GenesisBalance is one owner's available and locked atoms.
// Locked atoms must equal the reserves of that owner's active orders.
type GenesisBalance struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	AssetId              uint64   `protobuf:"varint,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Available            uint64   `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	Locked               uint64   `protobuf:"varint,4,opt,name=locked,proto3" json:"locked,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenesisBalance) Reset()         { *m = GenesisBalance{} }
func (m *GenesisBalance) String() string { return proto.CompactTextString(m) }
func (*GenesisBalance) ProtoMessage()    {}
func (*GenesisBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6075897526ec355, []int{1}
}
func (m *GenesisBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisBalance.Unmarshal(m, b)
}
func (m *GenesisBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisBalance.Marshal(b, m, deterministic)
}
func (m *GenesisBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisBalance.Merge(m, src)
}
func (m *GenesisBalance) XXX_Size() int {
	return xxx_messageInfo_GenesisBalance.Size(m)
}
func (m *GenesisBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisBalance.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisBalance proto.InternalMessageInfo

func (m *GenesisBalance) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *GenesisBalance) GetAssetId() uint64 {
	if m != nil {
		return m.AssetId
	}
	return 0
}

func (m *GenesisBalance) GetAvailable() uint64 {
	if m != nil {
		return m.Available
	}
	return 0
}

func (m *GenesisBalance) GetLocked() uint64 {
	if m != nil {
		return m.Locked
	}
	return 0
}

// GenesisOrder is one resting order plus the fee grosses needed to
// continue cumulative fee rounding. ClientOrderID is empty when the
// order has no active client id. Indexes are not stored here.
type GenesisOrder struct {
	OrderId              []byte      `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Owner                string      `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	MarketId             uint64      `protobuf:"varint,3,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Side                 Side        `protobuf:"varint,4,opt,name=side,proto3,enum=cosmosorderbook.exchange.v1.Side" json:"side,omitempty"`
	OrderType            OrderType   `protobuf:"varint,5,opt,name=order_type,json=orderType,proto3,enum=cosmosorderbook.exchange.v1.OrderType" json:"order_type,omitempty"`
	TimeInForce          TimeInForce `protobuf:"varint,6,opt,name=time_in_force,json=timeInForce,proto3,enum=cosmosorderbook.exchange.v1.TimeInForce" json:"time_in_force,omitempty"`
	PriceTicks           uint64      `protobuf:"varint,7,opt,name=price_ticks,json=priceTicks,proto3" json:"price_ticks,omitempty"`
	OriginalLots         uint64      `protobuf:"varint,8,opt,name=original_lots,json=originalLots,proto3" json:"original_lots,omitempty"`
	RemainingLots        uint64      `protobuf:"varint,9,opt,name=remaining_lots,json=remainingLots,proto3" json:"remaining_lots,omitempty"`
	Sequence             uint64      `protobuf:"varint,10,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ExpiryHeight         uint64      `protobuf:"varint,11,opt,name=expiry_height,json=expiryHeight,proto3" json:"expiry_height,omitempty"`
	CommandNonce         uint64      `protobuf:"varint,12,opt,name=command_nonce,json=commandNonce,proto3" json:"command_nonce,omitempty"`
	TakerGross           uint64      `protobuf:"varint,13,opt,name=taker_gross,json=takerGross,proto3" json:"taker_gross,omitempty"`
	MakerGross           uint64      `protobuf:"varint,14,opt,name=maker_gross,json=makerGross,proto3" json:"maker_gross,omitempty"`
	ClientOrderId        []byte      `protobuf:"bytes,15,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GenesisOrder) Reset()         { *m = GenesisOrder{} }
func (m *GenesisOrder) String() string { return proto.CompactTextString(m) }
func (*GenesisOrder) ProtoMessage()    {}
func (*GenesisOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6075897526ec355, []int{2}
}
func (m *GenesisOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisOrder.Unmarshal(m, b)
}
func (m *GenesisOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisOrder.Marshal(b, m, deterministic)
}
func (m *GenesisOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisOrder.Merge(m, src)
}
func (m *GenesisOrder) XXX_Size() int {
	return xxx_messageInfo_GenesisOrder.Size(m)
}
func (m *GenesisOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisOrder.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisOrder proto.InternalMessageInfo

func (m *GenesisOrder) GetOrderId() []byte {
	if m != nil {
		return m.OrderId
	}
	return nil
}

func (m *GenesisOrder) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *GenesisOrder) GetMarketId() uint64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *GenesisOrder) GetSide() Side {
	if m != nil {
		return m.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (m *GenesisOrder) GetOrderType() OrderType {
	if m != nil {
		return m.OrderType
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (m *GenesisOrder) GetTimeInForce() TimeInForce {
	if m != nil {
		return m.TimeInForce
	}
	return TimeInForce_TIME_IN_FORCE_UNSPECIFIED
}

func (m *GenesisOrder) GetPriceTicks() uint64 {
	if m != nil {
		return m.PriceTicks
	}
	return 0
}

func (m *GenesisOrder) GetOriginalLots() uint64 {
	if m != nil {
		return m.OriginalLots
	}
	return 0
}

func (m *GenesisOrder) GetRemainingLots() uint64 {
	if m != nil {
		return m.RemainingLots
	}
	return 0
}

func (m *GenesisOrder) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *GenesisOrder) GetExpiryHeight() uint64 {
	if m != nil {
		return m.ExpiryHeight
	}
	return 0
}

func (m *GenesisOrder) GetCommandNonce() uint64 {
	if m != nil {
		return m.CommandNonce
	}
	return 0
}

func (m *GenesisOrder) GetTakerGross() uint64 {
	if m != nil {
		return m.TakerGross
	}
	return 0
}

func (m *GenesisOrder) GetMakerGross() uint64 {
	if m != nil {
		return m.MakerGross
	}
	return 0
}

func (m *GenesisOrder) GetClientOrderId() []byte {
	if m != nil {
		return m.ClientOrderId
	}
	return nil
}

type AccountNonce struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Nonce                uint64   `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountNonce) Reset()         { *m = AccountNonce{} }
func (m *AccountNonce) String() string { return proto.CompactTextString(m) }
func (*AccountNonce) ProtoMessage()    {}
func (*AccountNonce) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6075897526ec355, []int{3}
}
func (m *AccountNonce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountNonce.Unmarshal(m, b)
}
func (m *AccountNonce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountNonce.Marshal(b, m, deterministic)
}
func (m *AccountNonce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountNonce.Merge(m, src)
}
func (m *AccountNonce) XXX_Size() int {
	return xxx_messageInfo_AccountNonce.Size(m)
}
func (m *AccountNonce) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountNonce.DiscardUnknown(m)
}

var xxx_messageInfo_AccountNonce proto.InternalMessageInfo

func (m *AccountNonce) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *AccountNonce) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

type MarketSequence struct {
	MarketId             uint64   `protobuf:"varint,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Sequence             uint64   `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketSequence) Reset()         { *m = MarketSequence{} }
func (m *MarketSequence) String() string { return proto.CompactTextString(m) }
func (*MarketSequence) ProtoMessage()    {}
func (*MarketSequence) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6075897526ec355, []int{4}
}
func (m *MarketSequence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketSequence.Unmarshal(m, b)
}
func (m *MarketSequence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketSequence.Marshal(b, m, deterministic)
}
func (m *MarketSequence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketSequence.Merge(m, src)
}
func (m *MarketSequence) XXX_Size() int {
	return xxx_messageInfo_MarketSequence.Size(m)
}
func (m *MarketSequence) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketSequence.DiscardUnknown(m)
}

var xxx_messageInfo_MarketSequence proto.InternalMessageInfo

func (m *MarketSequence) GetMarketId() uint64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *MarketSequence) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "cosmosorderbook.exchange.v1.GenesisState")
	proto.RegisterType((*GenesisBalance)(nil), "cosmosorderbook.exchange.v1.GenesisBalance")
	proto.RegisterType((*GenesisOrder)(nil), "cosmosorderbook.exchange.v1.GenesisOrder")
	proto.RegisterType((*AccountNonce)(nil), "cosmosorderbook.exchange.v1.AccountNonce")
	proto.RegisterType((*MarketSequence)(nil), "cosmosorderbook.exchange.v1.MarketSequence")
}

func init() {
	proto.RegisterFile("cosmosorderbook/exchange/v1/genesis.proto", fileDescriptor_a6075897526ec355)
}

var fileDescriptor_a6075897526ec355 = []byte{
	// 718 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x5d, 0x6b, 0xdb, 0x48,
	0x14, 0xc5, 0x8e, 0x3f, 0xc7, 0x1f, 0x81, 0x21, 0x2c, 0xda, 0x64, 0x61, 0xb3, 0x0e, 0x9b, 0x3a,
	0x94, 0xd8, 0x49, 0x4a, 0x5e, 0x02, 0x7d, 0x48, 0xa0, 0x49, 0x0c, 0x69, 0x03, 0x8a, 0x9f, 0xfa,
	0x22, 0xc6, 0xd2, 0xad, 0x3c, 0xd8, 0x9a, 0x71, 0x67, 0xc6, 0x4e, 0xfc, 0x83, 0xfb, 0x33, 0x0a,
	0x65, 0xee, 0x48, 0xfe, 0x08, 0x54, 0x84, 0xbe, 0xf9, 0x1e, 0x9d, 0x73, 0xe6, 0xde, 0xab, 0x33,
	0x16, 0x39, 0x09, 0xa5, 0x4e, 0xa4, 0x96, 0x2a, 0x02, 0x35, 0x92, 0x72, 0xd2, 0x87, 0x97, 0x70,
	0xcc, 0x44, 0x0c, 0xfd, 0xc5, 0x79, 0x3f, 0x06, 0x01, 0x9a, 0xeb, 0xde, 0x4c, 0x49, 0x23, 0xe9,
	0xc1, 0x2b, 0x6a, 0x2f, 0xa3, 0xf6, 0x16, 0xe7, 0xfb, 0xef, 0xf2, 0x7c, 0xcc, 0x72, 0x06, 0xa9,
	0x4b, 0xe7, 0x67, 0x89, 0x34, 0xef, 0x9c, 0xef, 0x93, 0x61, 0x06, 0xe8, 0xbf, 0xa4, 0xc1, 0x85,
	0x36, 0x4c, 0x84, 0x10, 0xf0, 0xc8, 0x2b, 0x1c, 0x16, 0xba, 0x75, 0x9f, 0x64, 0xd0, 0x20, 0xa2,
	0x57, 0xa4, 0xc2, 0xb4, 0x06, 0xa3, 0xbd, 0xe2, 0xe1, 0x4e, 0xb7, 0x71, 0xd1, 0xe9, 0xe5, 0x34,
	0xd2, 0xbb, 0xb6, 0x54, 0x3f, 0x55, 0xd0, 0x8f, 0xa4, 0x9a, 0x30, 0x35, 0xb1, 0xe2, 0x1d, 0x14,
	0x1f, 0xe5, 0x8a, 0x3f, 0x23, 0xd7, 0xcf, 0x34, 0xf4, 0x8e, 0xd4, 0x46, 0x6c, 0x6a, 0xfb, 0xd0,
	0x5e, 0x09, 0xf5, 0xef, 0x73, 0xf5, 0xe9, 0x60, 0x37, 0x4e, 0xe3, 0xaf, 0xc4, 0xf4, 0x9a, 0x54,
	0x84, 0x44, 0x9b, 0x32, 0xda, 0x9c, 0xe4, 0xcf, 0x10, 0x86, 0x72, 0x2e, 0xcc, 0x17, 0xab, 0xf0,
	0x53, 0x21, 0x1d, 0x92, 0x5d, 0x64, 0x07, 0x1a, 0xbe, 0xcf, 0x01, 0xbd, 0x2a, 0x6f, 0x68, 0xc9,
	0x8d, 0xf4, 0x94, 0x6a, 0xfc, 0x36, 0xb2, 0xb2, 0x12, 0x5d, 0x8d, 0x62, 0x11, 0x6c, 0xb8, 0x56,
	0xff, 0xc0, 0x15, 0x3d, 0xd6, 0xae, 0xfb, 0xa4, 0xa6, 0x60, 0xc1, 0x35, 0x97, 0xc2, 0xab, 0x1d,
	0x16, 0xba, 0x25, 0x7f, 0x55, 0xdb, 0x55, 0xa0, 0xa7, 0xf6, 0xea, 0x6f, 0x58, 0x45, 0xba, 0xd1,
	0x47, 0xfb, 0xd0, 0x4f, 0x85, 0x36, 0x11, 0x78, 0xa0, 0xf6, 0xc8, 0x1b, 0x12, 0x31, 0xb4, 0x54,
	0x3f, 0x55, 0x74, 0x9e, 0x49, 0x7b, 0xfb, 0x2d, 0xd1, 0x3d, 0x52, 0x96, 0xcf, 0x02, 0x54, 0x1a,
	0x3d, 0x57, 0xd0, 0xbf, 0x49, 0x0d, 0x33, 0x64, 0x33, 0x59, 0xc4, 0x11, 0xaa, 0x58, 0x0f, 0x22,
	0xfa, 0x0f, 0xa9, 0xb3, 0x05, 0xe3, 0x53, 0x36, 0x9a, 0x82, 0xb7, 0x83, 0xcf, 0xd6, 0x00, 0xfd,
	0x8b, 0x54, 0xa6, 0x32, 0x9c, 0x40, 0xe4, 0x95, 0xf0, 0x51, 0x5a, 0x75, 0x7e, 0xac, 0x83, 0x8f,
	0xd3, 0xd8, 0x13, 0xdc, 0x0b, 0x4d, 0x53, 0xdf, 0xf4, 0xab, 0x58, 0x0f, 0xa2, 0x75, 0x4b, 0xc5,
	0xcd, 0x96, 0x0e, 0x48, 0xdd, 0x05, 0xd3, 0x2a, 0xdc, 0xb9, 0x35, 0x07, 0x0c, 0x22, 0x7a, 0x49,
	0x4a, 0x9a, 0x47, 0x80, 0x87, 0xb6, 0x2f, 0xfe, 0xcb, 0xdd, 0xc8, 0x13, 0x8f, 0xc0, 0x47, 0x3a,
	0xfd, 0x44, 0x88, 0x6b, 0xc2, 0xde, 0x51, 0xaf, 0x8c, 0xe2, 0xe3, 0x5c, 0x31, 0x36, 0x3f, 0x5c,
	0xce, 0xc0, 0xaf, 0xcb, 0xec, 0x27, 0x7d, 0x20, 0x2d, 0xc3, 0x13, 0x08, 0xb8, 0x08, 0xbe, 0x49,
	0x15, 0x82, 0x57, 0x41, 0xa7, 0x6e, 0xfe, 0x8b, 0xe1, 0x09, 0x0c, 0xc4, 0xad, 0xe5, 0xfb, 0x0d,
	0xb3, 0x2e, 0xec, 0x5f, 0xc2, 0x4c, 0xf1, 0x10, 0x02, 0xc3, 0xc3, 0x89, 0x0d, 0xa4, 0x1d, 0x95,
	0x20, 0x34, 0xb4, 0x08, 0x3d, 0x22, 0x2d, 0xa9, 0x78, 0xcc, 0x05, 0x9b, 0x06, 0x53, 0x69, 0x74,
	0x1a, 0xb2, 0x66, 0x06, 0x3e, 0x48, 0xa3, 0xe9, 0xff, 0xa4, 0xad, 0x20, 0x61, 0x5c, 0x70, 0x11,
	0x3b, 0x56, 0x1d, 0x59, 0xad, 0x15, 0x8a, 0xb4, 0x7d, 0x52, 0xcb, 0xb2, 0xef, 0x11, 0xb7, 0xd4,
	0xac, 0xb6, 0xe7, 0xc0, 0xcb, 0x8c, 0xab, 0x65, 0x30, 0x06, 0x1e, 0x8f, 0x8d, 0xd7, 0x70, 0xe7,
	0x38, 0xf0, 0x1e, 0x31, 0x4b, 0x0a, 0x65, 0x92, 0x30, 0x11, 0x05, 0x78, 0x55, 0xbd, 0xa6, 0x23,
	0xa5, 0x20, 0xde, 0x62, 0x3b, 0x92, 0x61, 0x13, 0x50, 0x41, 0xac, 0xa4, 0xd6, 0x5e, 0xcb, 0x8d,
	0x84, 0xd0, 0x9d, 0x45, 0x2c, 0x21, 0xd9, 0x20, 0xb4, 0x1d, 0x21, 0x59, 0x13, 0x8e, 0xc9, 0x6e,
	0x38, 0xe5, 0x20, 0x4c, 0xb0, 0x4a, 0xcd, 0x2e, 0xa6, 0xa6, 0xe5, 0xe0, 0x47, 0x97, 0x9d, 0xce,
	0x15, 0x69, 0x6e, 0xfe, 0x7f, 0xfc, 0x26, 0xde, 0x7b, 0xa4, 0xec, 0x9a, 0x75, 0xd9, 0x76, 0x45,
	0x67, 0x40, 0xda, 0xdb, 0x37, 0x7b, 0x3b, 0x73, 0x85, 0x57, 0x99, 0xdb, 0x5c, 0x5d, 0x71, 0x7b,
	0x75, 0x37, 0xf7, 0x5f, 0x6f, 0x63, 0x6e, 0xc6, 0xf3, 0x51, 0x2f, 0x94, 0x49, 0x9f, 0x2d, 0xe7,
	0x7a, 0x9c, 0x70, 0x3d, 0x56, 0xec, 0xe2, 0xec, 0xec, 0xb2, 0xef, 0x62, 0x71, 0xba, 0xca, 0xc5,
	0x29, 0x88, 0x98, 0x0b, 0xe8, 0xbf, 0xac, 0xbf, 0x1b, 0xf8, 0xd1, 0xe8, 0x2f, 0xce, 0x47, 0x15,
	0xfc, 0x70, 0x7c, 0xf8, 0x35, 0x00, 0x78, 0x75, 0x50, 0x0c, 0xab, 0x06, 0x00, 0x00,
}
