// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmosorderbook/exchange/v1/types.proto

package v1

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Side matches the consensus values in pkg/domain.
type Side int32

const (
	Side_SIDE_UNSPECIFIED Side = 0
	Side_SIDE_BUY         Side = 1
	Side_SIDE_SELL        Side = 2
)

var Side_name = map[int32]string{
	0: "SIDE_UNSPECIFIED",
	1: "SIDE_BUY",
	2: "SIDE_SELL",
}

var Side_value = map[string]int32{
	"SIDE_UNSPECIFIED": 0,
	"SIDE_BUY":         1,
	"SIDE_SELL":        2,
}

func (x Side) String() string {
	return proto.EnumName(Side_name, int32(x))
}

func (Side) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0e541439d57e3ab5, []int{0}
}

// OrderType matches the consensus values in pkg/domain.
type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_ORDER_TYPE_LIMIT       OrderType = 1
	OrderType_ORDER_TYPE_MARKET      OrderType = 2
)

var OrderType_name = map[int32]string{
	0: "ORDER_TYPE_UNSPECIFIED",
	1: "ORDER_TYPE_LIMIT",
	2: "ORDER_TYPE_MARKET",
}

var OrderType_value = map[string]int32{
	"ORDER_TYPE_UNSPECIFIED": 0,
	"ORDER_TYPE_LIMIT":       1,
	"ORDER_TYPE_MARKET":      2,
}

func (x OrderType) String() string {
	return proto.EnumName(OrderType_name, int32(x))
}

func (OrderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0e541439d57e3ab5, []int{1}
}

// TimeInForce matches the consensus values in pkg/domain.
type TimeInForce int32

const (
	TimeInForce_TIME_IN_FORCE_UNSPECIFIED TimeInForce = 0
	TimeInForce_TIME_IN_FORCE_GTC         TimeInForce = 1
	TimeInForce_TIME_IN_FORCE_IOC         TimeInForce = 2
	TimeInForce_TIME_IN_FORCE_FOK         TimeInForce = 3
	TimeInForce_TIME_IN_FORCE_GTD         TimeInForce = 4
)

var TimeInForce_name = map[int32]string{
	0: "TIME_IN_FORCE_UNSPECIFIED",
	1: "TIME_IN_FORCE_GTC",
	2: "TIME_IN_FORCE_IOC",
	3: "TIME_IN_FORCE_FOK",
	4: "TIME_IN_FORCE_GTD",
}

var TimeInForce_value = map[string]int32{
	"TIME_IN_FORCE_UNSPECIFIED": 0,
	"TIME_IN_FORCE_GTC":         1,
	"TIME_IN_FORCE_IOC":         2,
	"TIME_IN_FORCE_FOK":         3,
	"TIME_IN_FORCE_GTD":         4,
}

func (x TimeInForce) String() string {
	return proto.EnumName(TimeInForce_name, int32(x))
}

func (TimeInForce) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0e541439d57e3ab5, []int{2}
}

// Asset is a bank denom registered for exchange custody.
type Asset struct {
	Id    uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Denom string `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (m *Asset) Reset()         { *m = Asset{} }
func (m *Asset) String() string { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()    {}
func (*Asset) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e541439d57e3ab5, []int{0}
}
func (m *Asset) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Asset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Asset.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Asset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Asset.Merge(m, src)
}
func (m *Asset) XXX_Size() int {
	return m.Size()
}
func (m *Asset) XXX_DiscardUnknown() {
	xxx_messageInfo_Asset.DiscardUnknown(m)
}

var xxx_messageInfo_Asset proto.InternalMessageInfo

func (m *Asset) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Asset) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// Market is one trading pair.
type Market struct {
	Id                      uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BaseAssetId             uint64 `protobuf:"varint,2,opt,name=base_asset_id,json=baseAssetId,proto3" json:"base_asset_id,omitempty"`
	QuoteAssetId            uint64 `protobuf:"varint,3,opt,name=quote_asset_id,json=quoteAssetId,proto3" json:"quote_asset_id,omitempty"`
	BaseLotSize             uint64 `protobuf:"varint,4,opt,name=base_lot_size,json=baseLotSize,proto3" json:"base_lot_size,omitempty"`
	QuoteAtomsPerTickPerLot uint64 `protobuf:"varint,5,opt,name=quote_atoms_per_tick_per_lot,json=quoteAtomsPerTickPerLot,proto3" json:"quote_atoms_per_tick_per_lot,omitempty"`
	MakerFeePpm             uint64 `protobuf:"varint,6,opt,name=maker_fee_ppm,json=makerFeePpm,proto3" json:"maker_fee_ppm,omitempty"`
	TakerFeePpm             uint64 `protobuf:"varint,7,opt,name=taker_fee_ppm,json=takerFeePpm,proto3" json:"taker_fee_ppm,omitempty"`
	MaxMakerVisits          uint32 `protobuf:"varint,8,opt,name=max_maker_visits,json=maxMakerVisits,proto3" json:"max_maker_visits,omitempty"`
	Enabled                 bool   `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	BaseDenom               string `protobuf:"bytes,10,opt,name=base_denom,json=baseDenom,proto3" json:"base_denom,omitempty"`
	QuoteDenom              string `protobuf:"bytes,11,opt,name=quote_denom,json=quoteDenom,proto3" json:"quote_denom,omitempty"`
}

func (m *Market) Reset()         { *m = Market{} }
func (m *Market) String() string { return proto.CompactTextString(m) }
func (*Market) ProtoMessage()    {}
func (*Market) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e541439d57e3ab5, []int{1}
}
func (m *Market) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Market) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Market.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Market) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Market.Merge(m, src)
}
func (m *Market) XXX_Size() int {
	return m.Size()
}
func (m *Market) XXX_DiscardUnknown() {
	xxx_messageInfo_Market.DiscardUnknown(m)
}

var xxx_messageInfo_Market proto.InternalMessageInfo

func (m *Market) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Market) GetBaseAssetId() uint64 {
	if m != nil {
		return m.BaseAssetId
	}
	return 0
}

func (m *Market) GetQuoteAssetId() uint64 {
	if m != nil {
		return m.QuoteAssetId
	}
	return 0
}

func (m *Market) GetBaseLotSize() uint64 {
	if m != nil {
		return m.BaseLotSize
	}
	return 0
}

func (m *Market) GetQuoteAtomsPerTickPerLot() uint64 {
	if m != nil {
		return m.QuoteAtomsPerTickPerLot
	}
	return 0
}

func (m *Market) GetMakerFeePpm() uint64 {
	if m != nil {
		return m.MakerFeePpm
	}
	return 0
}

func (m *Market) GetTakerFeePpm() uint64 {
	if m != nil {
		return m.TakerFeePpm
	}
	return 0
}

func (m *Market) GetMaxMakerVisits() uint32 {
	if m != nil {
		return m.MaxMakerVisits
	}
	return 0
}

func (m *Market) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Market) GetBaseDenom() string {
	if m != nil {
		return m.BaseDenom
	}
	return ""
}

func (m *Market) GetQuoteDenom() string {
	if m != nil {
		return m.QuoteDenom
	}
	return ""
}

// Balance is one owner's available and locked atoms for an asset.
type Balance struct {
	Owner     string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	AssetId   uint64 `protobuf:"varint,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Denom     string `protobuf:"bytes,3,opt,name=denom,proto3" json:"denom,omitempty"`
	Available uint64 `protobuf:"varint,4,opt,name=available,proto3" json:"available,omitempty"`
	Locked    uint64 `protobuf:"varint,5,opt,name=locked,proto3" json:"locked,omitempty"`
}

func (m *Balance) Reset()         { *m = Balance{} }
func (m *Balance) String() string { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()    {}
func (*Balance) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e541439d57e3ab5, []int{2}
}
func (m *Balance) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Balance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Balance.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Balance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Balance.Merge(m, src)
}
func (m *Balance) XXX_Size() int {
	return m.Size()
}
func (m *Balance) XXX_DiscardUnknown() {
	xxx_messageInfo_Balance.DiscardUnknown(m)
}

var xxx_messageInfo_Balance proto.InternalMessageInfo

func (m *Balance) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Balance) GetAssetId() uint64 {
	if m != nil {
		return m.AssetId
	}
	return 0
}

func (m *Balance) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *Balance) GetAvailable() uint64 {
	if m != nil {
		return m.Available
	}
	return 0
}

func (m *Balance) GetLocked() uint64 {
	if m != nil {
		return m.Locked
	}
	return 0
}

// Order is a live order returned by queries.
type Order struct {
	OrderId       []byte      `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Owner         string      `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	MarketId      uint64      `protobuf:"varint,3,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Side          Side        `protobuf:"varint,4,opt,name=side,proto3,enum=cosmosorderbook.exchange.v1.Side" json:"side,omitempty"`
	OrderType     OrderType   `protobuf:"varint,5,opt,name=order_type,json=orderType,proto3,enum=cosmosorderbook.exchange.v1.OrderType" json:"order_type,omitempty"`
	TimeInForce   TimeInForce `protobuf:"varint,6,opt,name=time_in_force,json=timeInForce,proto3,enum=cosmosorderbook.exchange.v1.TimeInForce" json:"time_in_force,omitempty"`
	PriceTicks    uint64      `protobuf:"varint,7,opt,name=price_ticks,json=priceTicks,proto3" json:"price_ticks,omitempty"`
	OriginalLots  uint64      `protobuf:"varint,8,opt,name=original_lots,json=originalLots,proto3" json:"original_lots,omitempty"`
	RemainingLots uint64      `protobuf:"varint,9,opt,name=remaining_lots,json=remainingLots,proto3" json:"remaining_lots,omitempty"`
	Sequence      uint64      `protobuf:"varint,10,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ExpiryHeight  uint64      `protobuf:"varint,11,opt,name=expiry_height,json=expiryHeight,proto3" json:"expiry_height,omitempty"`
	CommandNonce  uint64      `protobuf:"varint,12,opt,name=command_nonce,json=commandNonce,proto3" json:"command_nonce,omitempty"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e541439d57e3ab5, []int{3}
}
func (m *Order) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Order.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return m.Size()
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetOrderId() []byte {
	if m != nil {
		return m.OrderId
	}
	return nil
}

func (m *Order) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Order) GetMarketId() uint64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *Order) GetSide() Side {
	if m != nil {
		return m.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (m *Order) GetOrderType() OrderType {
	if m != nil {
		return m.OrderType
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (m *Order) GetTimeInForce() TimeInForce {
	if m != nil {
		return m.TimeInForce
	}
	return TimeInForce_TIME_IN_FORCE_UNSPECIFIED
}

func (m *Order) GetPriceTicks() uint64 {
	if m != nil {
		return m.PriceTicks
	}
	return 0
}

func (m *Order) GetOriginalLots() uint64 {
	if m != nil {
		return m.OriginalLots
	}
	return 0
}

func (m *Order) GetRemainingLots() uint64 {
	if m != nil {
		return m.RemainingLots
	}
	return 0
}

func (m *Order) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Order) GetExpiryHeight() uint64 {
	if m != nil {
		return m.ExpiryHeight
	}
	return 0
}

func (m *Order) GetCommandNonce() uint64 {
	if m != nil {
		return m.CommandNonce
	}
	return 0
}

// BookOrder is one resting order in canonical book order.
type BookOrder struct {
	OrderId       []byte `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Side          Side   `protobuf:"varint,2,opt,name=side,proto3,enum=cosmosorderbook.exchange.v1.Side" json:"side,omitempty"`
	PriceTicks    uint64 `protobuf:"varint,3,opt,name=price_ticks,json=priceTicks,proto3" json:"price_ticks,omitempty"`
	RemainingLots uint64 `protobuf:"varint,4,opt,name=remaining_lots,json=remainingLots,proto3" json:"remaining_lots,omitempty"`
	Sequence      uint64 `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (m *BookOrder) Reset()         { *m = BookOrder{} }
func (m *BookOrder) String() string { return proto.CompactTextString(m) }
func (*BookOrder) ProtoMessage()    {}
func (*BookOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e541439d57e3ab5, []int{4}
}
func (m *BookOrder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BookOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BookOrder.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BookOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookOrder.Merge(m, src)
}
func (m *BookOrder) XXX_Size() int {
	return m.Size()
}
func (m *BookOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_BookOrder.DiscardUnknown(m)
}

var xxx_messageInfo_BookOrder proto.InternalMessageInfo

func (m *BookOrder) GetOrderId() []byte {
	if m != nil {
		return m.OrderId
	}
	return nil
}

func (m *BookOrder) GetSide() Side {
	if m != nil {
		return m.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (m *BookOrder) GetPriceTicks() uint64 {
	if m != nil {
		return m.PriceTicks
	}
	return 0
}

func (m *BookOrder) GetRemainingLots() uint64 {
	if m != nil {
		return m.RemainingLots
	}
	return 0
}

func (m *BookOrder) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

// Trade is one persisted fill.
type Trade struct {
	MarketId     uint64 `protobuf:"varint,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Sequence     uint64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	MakerOrderId []byte `protobuf:"bytes,3,opt,name=maker_order_id,json=makerOrderId,proto3" json:"maker_order_id,omitempty"`
	TakerOrderId []byte `protobuf:"bytes,4,opt,name=taker_order_id,json=takerOrderId,proto3" json:"taker_order_id,omitempty"`
	PriceTicks   uint64 `protobuf:"varint,5,opt,name=price_ticks,json=priceTicks,proto3" json:"price_ticks,omitempty"`
	QuantityLots uint64 `protobuf:"varint,6,opt,name=quantity_lots,json=quantityLots,proto3" json:"quantity_lots,omitempty"`
	BaseAmount   uint64 `protobuf:"varint,7,opt,name=base_amount,json=baseAmount,proto3" json:"base_amount,omitempty"`
	QuoteAmount  uint64 `protobuf:"varint,8,opt,name=quote_amount,json=quoteAmount,proto3" json:"quote_amount,omitempty"`
	MakerFee     uint64 `protobuf:"varint,9,opt,name=maker_fee,json=makerFee,proto3" json:"maker_fee,omitempty"`
	TakerFee     uint64 `protobuf:"varint,10,opt,name=taker_fee,json=takerFee,proto3" json:"taker_fee,omitempty"`
	Buyer        string `protobuf:"bytes,11,opt,name=buyer,proto3" json:"buyer,omitempty"`
	Seller       string `protobuf:"bytes,12,opt,name=seller,proto3" json:"seller,omitempty"`
}

func (m *Trade) Reset()         { *m = Trade{} }
func (m *Trade) String() string { return proto.CompactTextString(m) }
func (*Trade) ProtoMessage()    {}
func (*Trade) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e541439d57e3ab5, []int{5}
}
func (m *Trade) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Trade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Trade.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Trade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trade.Merge(m, src)
}
func (m *Trade) XXX_Size() int {
	return m.Size()
}
func (m *Trade) XXX_DiscardUnknown() {
	xxx_messageInfo_Trade.DiscardUnknown(m)
}

var xxx_messageInfo_Trade proto.InternalMessageInfo

func (m *Trade) GetMarketId() uint64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *Trade) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Trade) GetMakerOrderId() []byte {
	if m != nil {
		return m.MakerOrderId
	}
	return nil
}

func (m *Trade) GetTakerOrderId() []byte {
	if m != nil {
		return m.TakerOrderId
	}
	return nil
}

func (m *Trade) GetPriceTicks() uint64 {
	if m != nil {
		return m.PriceTicks
	}
	return 0
}

func (m *Trade) GetQuantityLots() uint64 {
	if m != nil {
		return m.QuantityLots
	}
	return 0
}

func (m *Trade) GetBaseAmount() uint64 {
	if m != nil {
		return m.BaseAmount
	}
	return 0
}

func (m *Trade) GetQuoteAmount() uint64 {
	if m != nil {
		return m.QuoteAmount
	}
	return 0
}

func (m *Trade) GetMakerFee() uint64 {
	if m != nil {
		return m.MakerFee
	}
	return 0
}

func (m *Trade) GetTakerFee() uint64 {
	if m != nil {
		return m.TakerFee
	}
	return 0
}

func (m *Trade) GetBuyer() string {
	if m != nil {
		return m.Buyer
	}
	return ""
}

func (m *Trade) GetSeller() string {
	if m != nil {
		return m.Seller
	}
	return ""
}

func init() {
	proto.RegisterEnum("cosmosorderbook.exchange.v1.Side", Side_name, Side_value)
	proto.RegisterEnum("cosmosorderbook.exchange.v1.OrderType", OrderType_name, OrderType_value)
	proto.RegisterEnum("cosmosorderbook.exchange.v1.TimeInForce", TimeInForce_name, TimeInForce_value)
	proto.RegisterType((*Asset)(nil), "cosmosorderbook.exchange.v1.Asset")
	proto.RegisterType((*Market)(nil), "cosmosorderbook.exchange.v1.Market")
	proto.RegisterType((*Balance)(nil), "cosmosorderbook.exchange.v1.Balance")
	proto.RegisterType((*Order)(nil), "cosmosorderbook.exchange.v1.Order")
	proto.RegisterType((*BookOrder)(nil), "cosmosorderbook.exchange.v1.BookOrder")
	proto.RegisterType((*Trade)(nil), "cosmosorderbook.exchange.v1.Trade")
}

func init() {
	proto.RegisterFile("cosmosorderbook/exchange/v1/types.proto", fileDescriptor_0e541439d57e3ab5)
}

var fileDescriptor_0e541439d57e3ab5 = []byte{
	// 1016 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0x4d, 0x6f, 0xdb, 0x46,
	0x10, 0x35, 0x25, 0xca, 0x16, 0x47, 0x1f, 0x60, 0x16, 0x49, 0xaa, 0x7c, 0x29, 0x8e, 0xea, 0xb6,
	0x82, 0x01, 0x4b, 0xb1, 0x8b, 0x1c, 0x7a, 0xe8, 0x21, 0xb6, 0xa5, 0x96, 0x88, 0x6c, 0x19, 0xb4,
	0x52, 0x20, 0xbd, 0xb0, 0x14, 0x39, 0x91, 0x16, 0x12, 0xb9, 0x32, 0xb9, 0x72, 0xad, 0xfc, 0x80,
	0xa2, 0xc7, 0xf6, 0x27, 0xf5, 0xd6, 0x63, 0x8e, 0x3d, 0x16, 0xf6, 0x5f, 0xe8, 0xb9, 0x28, 0x76,
	0x97, 0x94, 0x25, 0xd9, 0x70, 0xd0, 0x1b, 0xe7, 0xed, 0xdb, 0xd9, 0x9d, 0x37, 0x6f, 0x07, 0x84,
	0xaf, 0x3c, 0x16, 0x07, 0x2c, 0x66, 0x91, 0x8f, 0x51, 0x9f, 0xb1, 0x51, 0x13, 0x2f, 0xbc, 0xa1,
	0x1b, 0x0e, 0xb0, 0x79, 0xbe, 0xdb, 0xe4, 0xb3, 0x09, 0xc6, 0x8d, 0x49, 0xc4, 0x38, 0x23, 0x4f,
	0x56, 0x88, 0x8d, 0x94, 0xd8, 0x38, 0xdf, 0xad, 0xed, 0x40, 0xee, 0x75, 0x1c, 0x23, 0x27, 0x65,
	0xc8, 0x50, 0xbf, 0xa2, 0x6d, 0x6a, 0x75, 0xdd, 0xce, 0x50, 0x9f, 0xdc, 0x87, 0x9c, 0x8f, 0x21,
	0x0b, 0x2a, 0x99, 0x4d, 0xad, 0x6e, 0xd8, 0x2a, 0xa8, 0xfd, 0x9e, 0x85, 0xf5, 0x23, 0x37, 0x1a,
	0xdd, 0xb2, 0xa1, 0x06, 0xa5, 0xbe, 0x1b, 0xa3, 0xe3, 0x8a, 0x74, 0x0e, 0xf5, 0xe5, 0x46, 0xdd,
	0x2e, 0x08, 0x50, 0x1e, 0x61, 0xf9, 0x64, 0x0b, 0xca, 0x67, 0x53, 0xc6, 0x17, 0x48, 0x59, 0x49,
	0x2a, 0x4a, 0x34, 0x65, 0xa5, 0x99, 0xc6, 0x8c, 0x3b, 0x31, 0xfd, 0x80, 0x15, 0xfd, 0x3a, 0x53,
	0x87, 0xf1, 0x53, 0xfa, 0x01, 0xc9, 0xb7, 0xf0, 0x34, 0xc9, 0xc4, 0x59, 0x10, 0x3b, 0x13, 0x8c,
	0x1c, 0x4e, 0xbd, 0x91, 0xfc, 0x18, 0x33, 0x5e, 0xc9, 0xc9, 0x2d, 0x9f, 0xa9, 0xbc, 0x82, 0x72,
	0x82, 0x51, 0x8f, 0x7a, 0xa3, 0x13, 0x8c, 0x3a, 0x8c, 0x8b, 0x23, 0x02, 0x77, 0x84, 0x91, 0xf3,
	0x1e, 0xd1, 0x99, 0x4c, 0x82, 0xca, 0xba, 0x3a, 0x42, 0x82, 0x6d, 0xc4, 0x93, 0x49, 0x20, 0x38,
	0x7c, 0x89, 0xb3, 0xa1, 0x38, 0x7c, 0x81, 0x53, 0x07, 0x33, 0x70, 0x2f, 0x1c, 0x95, 0xeb, 0x9c,
	0xc6, 0x94, 0xc7, 0x95, 0xfc, 0xa6, 0x56, 0x2f, 0xd9, 0xe5, 0xc0, 0xbd, 0x38, 0x12, 0xf0, 0x0f,
	0x12, 0x25, 0x15, 0xd8, 0xc0, 0xd0, 0xed, 0x8f, 0xd1, 0xaf, 0x18, 0x9b, 0x5a, 0x3d, 0x6f, 0xa7,
	0x21, 0x79, 0x06, 0x20, 0xcb, 0x55, 0x72, 0x83, 0x94, 0xdb, 0x10, 0xc8, 0xa1, 0x00, 0xc8, 0x73,
	0x28, 0xa8, 0x4a, 0xd5, 0x7a, 0x41, 0xae, 0x83, 0x84, 0x24, 0xa1, 0xf6, 0x8b, 0x06, 0x1b, 0xfb,
	0xee, 0xd8, 0x0d, 0x3d, 0x14, 0x5d, 0x63, 0x3f, 0x87, 0x18, 0xc9, 0xbe, 0x18, 0xb6, 0x0a, 0xc8,
	0x23, 0xc8, 0xaf, 0x74, 0x65, 0xc3, 0x4d, 0xb4, 0x9e, 0xb7, 0x39, 0xbb, 0xd0, 0x66, 0xf2, 0x14,
	0x0c, 0xf7, 0xdc, 0xa5, 0x63, 0x71, 0xc1, 0x44, 0xfd, 0x6b, 0x80, 0x3c, 0x84, 0xf5, 0x31, 0xf3,
	0x46, 0xe8, 0x27, 0x2a, 0x27, 0x51, 0xed, 0x9f, 0x2c, 0xe4, 0xba, 0x91, 0xaf, 0x0e, 0x94, 0x76,
	0x73, 0x12, 0x87, 0x14, 0xed, 0x0d, 0x19, 0xab, 0x03, 0xd5, 0x0d, 0x33, 0x8b, 0x37, 0x7c, 0x02,
	0x46, 0x20, 0x6d, 0x75, 0xed, 0x89, 0xbc, 0x02, 0x2c, 0x9f, 0xbc, 0x02, 0x3d, 0xa6, 0xbe, 0xba,
	0x48, 0x79, 0xef, 0x45, 0xe3, 0x0e, 0x3f, 0x37, 0x4e, 0xa9, 0x8f, 0xb6, 0xa4, 0x93, 0x16, 0x80,
	0xba, 0x84, 0x78, 0x0c, 0xf2, 0xaa, 0xe5, 0xbd, 0x2f, 0xef, 0xdc, 0x2c, 0x2f, 0xdf, 0x9b, 0x4d,
	0xd0, 0x36, 0x58, 0xfa, 0x49, 0x3a, 0x50, 0xe2, 0x34, 0x40, 0x87, 0x86, 0xce, 0x7b, 0x16, 0x79,
	0x28, 0xad, 0x52, 0xde, 0xab, 0xdf, 0x99, 0xa9, 0x47, 0x03, 0xb4, 0xc2, 0xb6, 0xe0, 0xdb, 0x05,
	0x7e, 0x1d, 0x88, 0x6e, 0x4e, 0x22, 0xea, 0xa1, 0x74, 0x6b, 0x9c, 0x58, 0x0a, 0x24, 0x24, 0xec,
	0x19, 0x93, 0xcf, 0xa1, 0xc4, 0x22, 0x3a, 0xa0, 0xa1, 0x3b, 0x16, 0x46, 0x56, 0x76, 0xd2, 0xed,
	0x62, 0x0a, 0x76, 0x18, 0x8f, 0xc9, 0x17, 0x50, 0x8e, 0x30, 0x70, 0x69, 0x48, 0xc3, 0x81, 0x62,
	0x19, 0x92, 0x55, 0x9a, 0xa3, 0x92, 0xf6, 0x18, 0xf2, 0x31, 0x9e, 0x4d, 0x31, 0xf4, 0x50, 0xfa,
	0x4a, 0xb7, 0xe7, 0xb1, 0x38, 0x07, 0x2f, 0x26, 0x34, 0x9a, 0x39, 0x43, 0xa4, 0x83, 0x21, 0x97,
	0xc6, 0xd2, 0xed, 0xa2, 0x02, 0xbf, 0x97, 0x98, 0x20, 0x79, 0x2c, 0x08, 0xdc, 0xd0, 0x77, 0x42,
	0x26, 0xb2, 0x14, 0x15, 0x29, 0x01, 0x8f, 0x05, 0x56, 0xfb, 0x43, 0x03, 0x63, 0x9f, 0xb1, 0xd1,
	0x27, 0x5b, 0x9f, 0xf6, 0x31, 0xf3, 0xff, 0xfa, 0xb8, 0x22, 0x59, 0xf6, 0x86, 0x64, 0x37, 0xd5,
	0xd0, 0x3f, 0xa5, 0x46, 0x6e, 0x59, 0x8d, 0xda, 0xbf, 0x19, 0xc8, 0xf5, 0x22, 0xd7, 0xc7, 0x65,
	0x27, 0x6a, 0x2b, 0x4e, 0x5c, 0x4c, 0x91, 0x59, 0x11, 0x74, 0x0b, 0xca, 0x6a, 0x0c, 0xcc, 0xcb,
	0xcf, 0xca, 0xf2, 0x8b, 0x12, 0xed, 0x26, 0x1a, 0x6c, 0x41, 0x99, 0x2f, 0xb3, 0x74, 0xc5, 0xe2,
	0x8b, 0xac, 0x95, 0x92, 0x73, 0xb7, 0xb9, 0xe4, 0x6c, 0xea, 0x86, 0x9c, 0xf2, 0x99, 0xaa, 0x78,
	0x3d, 0x9d, 0xa3, 0x0a, 0x94, 0x05, 0x3f, 0x87, 0x82, 0x9a, 0xc8, 0x01, 0x9b, 0x86, 0x3c, 0xf5,
	0x9a, 0x9c, 0xc7, 0x12, 0x21, 0x2f, 0xa0, 0x98, 0x0c, 0x51, 0xc5, 0x50, 0x56, 0x53, 0xe3, 0x26,
	0xa1, 0x48, 0x39, 0x92, 0x21, 0x98, 0x98, 0x2c, 0x9f, 0x0e, 0x49, 0xb1, 0x38, 0x9f, 0x90, 0xa9,
	0xc1, 0xd2, 0xe9, 0x28, 0x1e, 0x7a, 0x7f, 0x3a, 0xc3, 0x28, 0x99, 0x58, 0x2a, 0x10, 0xb3, 0x23,
	0xc6, 0xf1, 0x18, 0x23, 0x69, 0x25, 0xc3, 0x4e, 0xa2, 0xed, 0x6f, 0x40, 0x17, 0x2d, 0x27, 0xf7,
	0xc1, 0x3c, 0xb5, 0x0e, 0x5b, 0xce, 0xdb, 0xe3, 0xd3, 0x93, 0xd6, 0x81, 0xd5, 0xb6, 0x5a, 0x87,
	0xe6, 0x1a, 0x29, 0x42, 0x5e, 0xa2, 0xfb, 0x6f, 0xdf, 0x99, 0x1a, 0x29, 0x81, 0x21, 0xa3, 0xd3,
	0x56, 0xa7, 0x63, 0x66, 0xb6, 0x7b, 0x60, 0xcc, 0x1f, 0x2e, 0x79, 0x0c, 0x0f, 0xbb, 0xf6, 0x61,
	0xcb, 0x76, 0x7a, 0xef, 0x4e, 0x56, 0xb3, 0xdc, 0x07, 0x73, 0x61, 0xad, 0x63, 0x1d, 0x59, 0x3d,
	0x53, 0x23, 0x0f, 0xe0, 0xde, 0x02, 0x7a, 0xf4, 0xda, 0x7e, 0xd3, 0xea, 0x99, 0x99, 0xed, 0x5f,
	0x35, 0x28, 0x2c, 0xbc, 0x62, 0xf2, 0x0c, 0x1e, 0xf5, 0xac, 0xa3, 0x96, 0x63, 0x1d, 0x3b, 0xed,
	0xae, 0x7d, 0xb0, 0x9a, 0xfb, 0x01, 0xdc, 0x5b, 0x5e, 0xfe, 0xae, 0x77, 0x60, 0x6a, 0x37, 0x61,
	0xab, 0x7b, 0x60, 0x66, 0x6e, 0xc2, 0xed, 0xee, 0x1b, 0x33, 0x7b, 0x5b, 0x92, 0x43, 0x53, 0xdf,
	0xff, 0xe9, 0xcf, 0xcb, 0xaa, 0xf6, 0xf1, 0xb2, 0xaa, 0xfd, 0x7d, 0x59, 0xd5, 0x7e, 0xbb, 0xaa,
	0xae, 0x7d, 0xbc, 0xaa, 0xae, 0xfd, 0x75, 0x55, 0x5d, 0xfb, 0xb1, 0x3d, 0xa0, 0x7c, 0x38, 0xed,
	0x37, 0x3c, 0x16, 0x34, 0xdd, 0xd9, 0x34, 0x1e, 0x06, 0x34, 0x1e, 0x46, 0xee, 0xde, 0xcb, 0x97,
	0xaf, 0x9a, 0xea, 0x75, 0xed, 0xcc, 0x9f, 0xd7, 0x0e, 0x86, 0x03, 0x1a, 0x62, 0xf3, 0xe2, 0xfa,
	0x47, 0x41, 0xfe, 0x25, 0x34, 0xcf, 0x77, 0xfb, 0xeb, 0xf2, 0x4f, 0xe1, 0xeb, 0xff, 0x06, 0x00,
	0x8f, 0x7f, 0x1d, 0x22, 0x54, 0x08, 0x00, 0x00,
}

func (m *Asset) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Asset) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Asset) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Market) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Market) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Market) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.QuoteDenom) > 0 {
		i -= len(m.QuoteDenom)
		copy(dAtA[i:], m.QuoteDenom)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.QuoteDenom)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.BaseDenom) > 0 {
		i -= len(m.BaseDenom)
		copy(dAtA[i:], m.BaseDenom)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.BaseDenom)))
		i--
		dAtA[i] = 0x52
	}
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if m.MaxMakerVisits != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MaxMakerVisits))
		i--
		dAtA[i] = 0x40
	}
	if m.TakerFeePpm != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.TakerFeePpm))
		i--
		dAtA[i] = 0x38
	}
	if m.MakerFeePpm != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MakerFeePpm))
		i--
		dAtA[i] = 0x30
	}
	if m.QuoteAtomsPerTickPerLot != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.QuoteAtomsPerTickPerLot))
		i--
		dAtA[i] = 0x28
	}
	if m.BaseLotSize != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.BaseLotSize))
		i--
		dAtA[i] = 0x20
	}
	if m.QuoteAssetId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.QuoteAssetId))
		i--
		dAtA[i] = 0x18
	}
	if m.BaseAssetId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.BaseAssetId))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Balance) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Balance) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Balance) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Locked != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Locked))
		i--
		dAtA[i] = 0x28
	}
	if m.Available != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Available))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x1a
	}
	if m.AssetId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.AssetId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Order) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Order) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Order) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CommandNonce != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CommandNonce))
		i--
		dAtA[i] = 0x60
	}
	if m.ExpiryHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ExpiryHeight))
		i--
		dAtA[i] = 0x58
	}
	if m.Sequence != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x50
	}
	if m.RemainingLots != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RemainingLots))
		i--
		dAtA[i] = 0x48
	}
	if m.OriginalLots != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.OriginalLots))
		i--
		dAtA[i] = 0x40
	}
	if m.PriceTicks != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.PriceTicks))
		i--
		dAtA[i] = 0x38
	}
	if m.TimeInForce != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.TimeInForce))
		i--
		dAtA[i] = 0x30
	}
	if m.OrderType != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.OrderType))
		i--
		dAtA[i] = 0x28
	}
	if m.Side != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Side))
		i--
		dAtA[i] = 0x20
	}
	if m.MarketId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MarketId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OrderId) > 0 {
		i -= len(m.OrderId)
		copy(dAtA[i:], m.OrderId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.OrderId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BookOrder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BookOrder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BookOrder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Sequence != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x28
	}
	if m.RemainingLots != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RemainingLots))
		i--
		dAtA[i] = 0x20
	}
	if m.PriceTicks != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.PriceTicks))
		i--
		dAtA[i] = 0x18
	}
	if m.Side != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Side))
		i--
		dAtA[i] = 0x10
	}
	if len(m.OrderId) > 0 {
		i -= len(m.OrderId)
		copy(dAtA[i:], m.OrderId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.OrderId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Trade) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Trade) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Trade) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Seller) > 0 {
		i -= len(m.Seller)
		copy(dAtA[i:], m.Seller)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Seller)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.Buyer) > 0 {
		i -= len(m.Buyer)
		copy(dAtA[i:], m.Buyer)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Buyer)))
		i--
		dAtA[i] = 0x5a
	}
	if m.TakerFee != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.TakerFee))
		i--
		dAtA[i] = 0x50
	}
	if m.MakerFee != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MakerFee))
		i--
		dAtA[i] = 0x48
	}
	if m.QuoteAmount != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.QuoteAmount))
		i--
		dAtA[i] = 0x40
	}
	if m.BaseAmount != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.BaseAmount))
		i--
		dAtA[i] = 0x38
	}
	if m.QuantityLots != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.QuantityLots))
		i--
		dAtA[i] = 0x30
	}
	if m.PriceTicks != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.PriceTicks))
		i--
		dAtA[i] = 0x28
	}
	if len(m.TakerOrderId) > 0 {
		i -= len(m.TakerOrderId)
		copy(dAtA[i:], m.TakerOrderId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.TakerOrderId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.MakerOrderId) > 0 {
		i -= len(m.MakerOrderId)
		copy(dAtA[i:], m.MakerOrderId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.MakerOrderId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Sequence != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x10
	}
	if m.MarketId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MarketId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Asset) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTypes(uint64(m.Id))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *Market) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTypes(uint64(m.Id))
	}
	if m.BaseAssetId != 0 {
		n += 1 + sovTypes(uint64(m.BaseAssetId))
	}
	if m.QuoteAssetId != 0 {
		n += 1 + sovTypes(uint64(m.QuoteAssetId))
	}
	if m.BaseLotSize != 0 {
		n += 1 + sovTypes(uint64(m.BaseLotSize))
	}
	if m.QuoteAtomsPerTickPerLot != 0 {
		n += 1 + sovTypes(uint64(m.QuoteAtomsPerTickPerLot))
	}
	if m.MakerFeePpm != 0 {
		n += 1 + sovTypes(uint64(m.MakerFeePpm))
	}
	if m.TakerFeePpm != 0 {
		n += 1 + sovTypes(uint64(m.TakerFeePpm))
	}
	if m.MaxMakerVisits != 0 {
		n += 1 + sovTypes(uint64(m.MaxMakerVisits))
	}
	if m.Enabled {
		n += 2
	}
	l = len(m.BaseDenom)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.QuoteDenom)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *Balance) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.AssetId != 0 {
		n += 1 + sovTypes(uint64(m.AssetId))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Available != 0 {
		n += 1 + sovTypes(uint64(m.Available))
	}
	if m.Locked != 0 {
		n += 1 + sovTypes(uint64(m.Locked))
	}
	return n
}

func (m *Order) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrderId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.MarketId != 0 {
		n += 1 + sovTypes(uint64(m.MarketId))
	}
	if m.Side != 0 {
		n += 1 + sovTypes(uint64(m.Side))
	}
	if m.OrderType != 0 {
		n += 1 + sovTypes(uint64(m.OrderType))
	}
	if m.TimeInForce != 0 {
		n += 1 + sovTypes(uint64(m.TimeInForce))
	}
	if m.PriceTicks != 0 {
		n += 1 + sovTypes(uint64(m.PriceTicks))
	}
	if m.OriginalLots != 0 {
		n += 1 + sovTypes(uint64(m.OriginalLots))
	}
	if m.RemainingLots != 0 {
		n += 1 + sovTypes(uint64(m.RemainingLots))
	}
	if m.Sequence != 0 {
		n += 1 + sovTypes(uint64(m.Sequence))
	}
	if m.ExpiryHeight != 0 {
		n += 1 + sovTypes(uint64(m.ExpiryHeight))
	}
	if m.CommandNonce != 0 {
		n += 1 + sovTypes(uint64(m.CommandNonce))
	}
	return n
}

func (m *BookOrder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrderId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Side != 0 {
		n += 1 + sovTypes(uint64(m.Side))
	}
	if m.PriceTicks != 0 {
		n += 1 + sovTypes(uint64(m.PriceTicks))
	}
	if m.RemainingLots != 0 {
		n += 1 + sovTypes(uint64(m.RemainingLots))
	}
	if m.Sequence != 0 {
		n += 1 + sovTypes(uint64(m.Sequence))
	}
	return n
}

func (m *Trade) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MarketId != 0 {
		n += 1 + sovTypes(uint64(m.MarketId))
	}
	if m.Sequence != 0 {
		n += 1 + sovTypes(uint64(m.Sequence))
	}
	l = len(m.MakerOrderId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.TakerOrderId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.PriceTicks != 0 {
		n += 1 + sovTypes(uint64(m.PriceTicks))
	}
	if m.QuantityLots != 0 {
		n += 1 + sovTypes(uint64(m.QuantityLots))
	}
	if m.BaseAmount != 0 {
		n += 1 + sovTypes(uint64(m.BaseAmount))
	}
	if m.QuoteAmount != 0 {
		n += 1 + sovTypes(uint64(m.QuoteAmount))
	}
	if m.MakerFee != 0 {
		n += 1 + sovTypes(uint64(m.MakerFee))
	}
	if m.TakerFee != 0 {
		n += 1 + sovTypes(uint64(m.TakerFee))
	}
	l = len(m.Buyer)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Seller)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Asset) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Asset: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Asset: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Market) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Market: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Market: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseAssetId", wireType)
			}
			m.BaseAssetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BaseAssetId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuoteAssetId", wireType)
			}
			m.QuoteAssetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.QuoteAssetId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseLotSize", wireType)
			}
			m.BaseLotSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BaseLotSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuoteAtomsPerTickPerLot", wireType)
			}
			m.QuoteAtomsPerTickPerLot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.QuoteAtomsPerTickPerLot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MakerFeePpm", wireType)
			}
			m.MakerFeePpm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MakerFeePpm |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TakerFeePpm", wireType)
			}
			m.TakerFeePpm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TakerFeePpm |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxMakerVisits", wireType)
			}
			m.MaxMakerVisits = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxMakerVisits |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuoteDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QuoteDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Balance) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Balance: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Balance: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			m.AssetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Available", wireType)
			}
			m.Available = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Available |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Locked", wireType)
			}
			m.Locked = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Locked |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Order) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Order: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Order: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderId = append(m.OrderId[:0], dAtA[iNdEx:postIndex]...)
			if m.OrderId == nil {
				m.OrderId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketId", wireType)
			}
			m.MarketId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MarketId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Side", wireType)
			}
			m.Side = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Side |= Side(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderType", wireType)
			}
			m.OrderType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OrderType |= OrderType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeInForce", wireType)
			}
			m.TimeInForce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeInForce |= TimeInForce(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceTicks", wireType)
			}
			m.PriceTicks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PriceTicks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OriginalLots", wireType)
			}
			m.OriginalLots = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OriginalLots |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainingLots", wireType)
			}
			m.RemainingLots = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RemainingLots |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiryHeight", wireType)
			}
			m.ExpiryHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiryHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommandNonce", wireType)
			}
			m.CommandNonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommandNonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BookOrder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BookOrder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BookOrder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderId = append(m.OrderId[:0], dAtA[iNdEx:postIndex]...)
			if m.OrderId == nil {
				m.OrderId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Side", wireType)
			}
			m.Side = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Side |= Side(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceTicks", wireType)
			}
			m.PriceTicks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PriceTicks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainingLots", wireType)
			}
			m.RemainingLots = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RemainingLots |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Trade) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Trade: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Trade: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketId", wireType)
			}
			m.MarketId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MarketId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MakerOrderId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MakerOrderId = append(m.MakerOrderId[:0], dAtA[iNdEx:postIndex]...)
			if m.MakerOrderId == nil {
				m.MakerOrderId = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TakerOrderId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TakerOrderId = append(m.TakerOrderId[:0], dAtA[iNdEx:postIndex]...)
			if m.TakerOrderId == nil {
				m.TakerOrderId = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceTicks", wireType)
			}
			m.PriceTicks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PriceTicks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuantityLots", wireType)
			}
			m.QuantityLots = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.QuantityLots |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseAmount", wireType)
			}
			m.BaseAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BaseAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuoteAmount", wireType)
			}
			m.QuoteAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.QuoteAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MakerFee", wireType)
			}
			m.MakerFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MakerFee |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TakerFee", wireType)
			}
			m.TakerFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TakerFee |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buyer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Buyer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seller", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Seller = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
